// MY GERMAN DÖNER — Master Catalog Data & Asset Intelligence Vault
// Synchronized with official 2026 4K Digital Menu Boards and store operations.
// Provides 100% offline resilience and high-res local imagery for Web, POS, Kiosks & Signage.

export interface MasterCatalogProduct {
  id: string;
  categoryId: string;
  sku: string;
  name: string;
  nameDE?: string;
  nameGR?: string;
  description: string;
  descriptionDE?: string;
  descriptionGR?: string;
  basePrice: number;
  vatCategory: "FOOD_BEV" | "ALCOHOL" | "ZERO";
  imageUrl: string;
  badge?: string;
  calories?: number;
  allergens?: string[];
  isVeggie?: boolean;
  isSpicy?: boolean;
  isAvailable: boolean;
  allowMealUpgrade: boolean;
  sortOrder: number;
}

export interface MasterCatalogCategory {
  id: string;
  slug: string;
  name: string;
  nameDE: string;
  nameGR: string;
  description?: string;
  sortOrder: number;
  isActive: boolean;
  products: MasterCatalogProduct[];
}

export const CANONICAL_CATALOG_CATEGORIES: MasterCatalogCategory[] = [
  // 1. DÖNER BUNS
  {
    id: "cat-doner-buns",
    slug: "doner-buns",
    name: "Döner Buns",
    nameDE: "Berliner Döner Taschen",
    nameGR: "Ντόνερ σε Ψωμί",
    description: "Caramelized rotisserie meat served in freshly baked toasted sesame flatbread.",
    sortOrder: 1,
    isActive: true,
    products: [
      {
        id: "prod-hamburg-doner",
        categoryId: "cat-doner-buns",
        sku: "MYGD-B1-HMB-DONER",
        name: "Hamburg Doener",
        nameDE: "Hamburger Döner Kebab",
        nameGR: "Χάμπουργκ Ντόνερ",
        description: "Rotisserie doener meat, fresh lettuce, tomato, cucumber, fresh onions, red cabbage. Sauces: Ketchup, Mayo, Mustard.",
        descriptionDE: "Dönerfleisch, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Saucen: Ketchup, Mayo, Senf.",
        basePrice: 6.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/hamburg-doener.jpg",
        badge: "POPULAR",
        calories: 680,
        allergens: ["Gluten", "Egg", "Mustard", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 1,
      },
      {
        id: "prod-chicken-doner",
        categoryId: "cat-doner-buns",
        sku: "MYGD-B1-CK-DONER",
        name: "Chicken Doener",
        nameDE: "Hähnchen Döner Kebab",
        nameGR: "Ντόνερ Κοτόπουλο",
        description: "Juicy chicken doener, crisp lettuce, tomato, cucumber, fresh onions, red cabbage. Sauces: Ketchup, Mayo.",
        descriptionDE: "Saftiges Hähnchendönerfleisch, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Saucen: Ketchup, Mayo.",
        basePrice: 6.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/chicken-doener.webp",
        badge: "BESTSELLER",
        calories: 620,
        allergens: ["Gluten", "Egg", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 2,
      },
      {
        id: "prod-cheese-doner",
        categoryId: "cat-doner-buns",
        sku: "MYGD-B1-CHS-DONER",
        name: "Cheese Doener",
        nameDE: "Käse Döner Kebab",
        nameGR: "Ντόνερ με Τυρί",
        description: "Savory doener meat, melted cheese, lettuce, tomato, cucumber, onions, red cabbage. Sauce: BBQ.",
        descriptionDE: "Dönerfleisch mit geschmolzenem Käse, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Sauce: BBQ.",
        basePrice: 7.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/cheese-doener.webp",
        badge: "POPULAR",
        calories: 760,
        allergens: ["Gluten", "Dairy", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 3,
      },
      {
        id: "prod-cheese-chicken-doner",
        categoryId: "cat-doner-buns",
        sku: "MYGD-B1-CHS-CK-DONER",
        name: "Cheese Chicken Doener",
        nameDE: "Käse Hähnchen Döner",
        nameGR: "Ντόνερ Κοτόπουλο με Τυρί",
        description: "Tender chicken doener, melted cheese, crisp lettuce, tomato, cucumber, onions, red cabbage. Sauces: Ketchup, Mayo.",
        descriptionDE: "Hähnchendöner mit geschmolzenem Käse, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Saucen: Ketchup, Mayo.",
        basePrice: 7.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/cheese-chicken-doener.webp",
        calories: 710,
        allergens: ["Gluten", "Dairy", "Egg", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 4,
      },
    ],
  },

  // 2. MY WRAPS
  {
    id: "cat-wraps",
    slug: "my-wraps",
    name: "My Wraps",
    nameDE: "Berliner Dürüm Wraps",
    nameGR: "Τυλιχτά Wraps",
    description: "Rolled in warm lavash flatbread with garden-fresh salads and specialty sauces.",
    sortOrder: 2,
    isActive: true,
    products: [
      {
        id: "prod-beef-wrap",
        categoryId: "cat-wraps",
        sku: "MYGD-B1-BF-WRAP",
        name: "Beef Wrap",
        nameDE: "Rind Dürüm Wrap",
        nameGR: "Τυλιχτό Μοσχάρι",
        description: "Beef doener, fresh lettuce, tomato, cucumber, onions, red cabbage. Sauce: Cocktail.",
        descriptionDE: "Rinder-Döner, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Sauce: Cocktail.",
        basePrice: 9.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/beef-wrap.jpg",
        badge: "TOP_SELLER",
        calories: 690,
        allergens: ["Gluten", "Egg", "Mustard"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 1,
      },
      {
        id: "prod-chicken-wrap",
        categoryId: "cat-wraps",
        sku: "MYGD-B1-CK-WRAP",
        name: "Chicken Wrap",
        nameDE: "Hähnchen Dürüm Wrap",
        nameGR: "Τυλιχτό Κοτόπουλο",
        description: "Chicken doener, crisp lettuce, tomato, cucumber, onions, red cabbage. Sauce: Garlic.",
        descriptionDE: "Hähnchendöner, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Sauce: Knoblauchsauce.",
        basePrice: 9.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/chicken-wrap.webp",
        badge: "BESTSELLER",
        calories: 630,
        allergens: ["Gluten", "Dairy", "Egg"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 2,
      },
      {
        id: "prod-mix-wrap",
        categoryId: "cat-wraps",
        sku: "MYGD-B1-MIX-WRAP",
        name: "Mix Wrap",
        nameDE: "Mix Dürüm Wrap (Rind & Huhn)",
        nameGR: "Μιξ Τυλιχτό (Μοσχάρι & Κοτόπουλο)",
        description: "Beef & chicken doener combination, lettuce, tomato, cucumber, onions, red cabbage. Sauce: Lemon Herb.",
        descriptionDE: "Dönerfleisch Mix aus Rind und Hähnchen, Salat, Tomate, Gurke, Zwiebel, Rotkohl. Sauce: Lemon Herb.",
        basePrice: 9.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/mix-wrap.webp",
        calories: 660,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 3,
      },
      {
        id: "prod-vegan-wrap",
        categoryId: "cat-wraps",
        sku: "MYGD-B1-VGN-WRAP",
        name: "Vegan Wrap",
        nameDE: "Veganer Bällchen Wrap",
        nameGR: "Vegan Τυλιχτό",
        description: "Plant-based vegan balls, crisp lettuce, tomato, cucumber, onions, red cabbage. Sauce: Vegan Garlic.",
        descriptionDE: "Vegane Bällchen, knackiger Salat, Tomate, Gurke, Zwiebel, Rotkohl. Sauce: Vegane Knoblauchsauce.",
        basePrice: 9.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/vegan-wrap.webp",
        badge: "VEGGIE",
        calories: 540,
        allergens: ["Gluten", "Soy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 4,
      },
    ],
  },

  // 3. MY BIG'S
  {
    id: "cat-bigs",
    slug: "my-bigs",
    name: "My Big's",
    nameDE: "My Big's XXL Berliner Fladenbrot",
    nameGR: "My Big's XXL",
    description: "Massive portions served in original Berlin triangular toasted flatbread.",
    sortOrder: 3,
    isActive: true,
    products: [
      {
        id: "prod-big-b",
        categoryId: "cat-bigs",
        sku: "MYGD-B1-BIG-B",
        name: "Big B",
        nameDE: "Big B XXL Rind Döner",
        nameGR: "Big B Μοσχάρι",
        description: "Beef doener, original Berlin flatbread, lettuce, tomato, cucumber, onions, red cabbage. Sauce: Cocktail.",
        descriptionDE: "Rind-Dönerfleisch im original Berliner Fladenbrot, Salat, Tomate, Gurke, Zwiebel, Rotkohl. Sauce: Cocktail.",
        basePrice: 11.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/big-b-doener.jpg",
        badge: "CHEF_CHOICE",
        calories: 920,
        allergens: ["Gluten", "Egg", "Mustard", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 1,
      },
      {
        id: "prod-big-chick",
        categoryId: "cat-bigs",
        sku: "MYGD-B1-BIG-CHICK",
        name: "Big Chick",
        nameDE: "Big Chick XXL Hähnchen Döner",
        nameGR: "Big Chick Κοτόπουλο",
        description: "Chicken doener, original Berlin flatbread, lettuce, tomato, cucumber, onions, red cabbage. Sauce: Garlic.",
        descriptionDE: "Hähnchendönerfleisch im original Berliner Fladenbrot, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Sauce: Knoblauch.",
        basePrice: 11.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/big-chick.webp",
        badge: "POPULAR",
        calories: 860,
        allergens: ["Gluten", "Dairy", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 2,
      },
      {
        id: "prod-big-mix",
        categoryId: "cat-bigs",
        sku: "MYGD-B1-BIG-MIX",
        name: "Big Mix",
        nameDE: "Big Mix XXL (Rind & Huhn)",
        nameGR: "Big Mix (Μοσχάρι & Κοτόπουλο)",
        description: "Beef & chicken doener, original Berlin flatbread, lettuce, tomato, cucumber, onions, red cabbage. Sauce: Lemon Herb.",
        descriptionDE: "Rind & Hähnchendöner im Berliner Fladenbrot, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Sauce: Lemon Herb.",
        basePrice: 11.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/big-mix.webp",
        calories: 890,
        allergens: ["Gluten", "Dairy", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 3,
      },
      {
        id: "prod-big-green",
        categoryId: "cat-bigs",
        sku: "MYGD-B1-BIG-GREEN",
        name: "Big Green",
        nameDE: "Big Green XXL (Vegan)",
        nameGR: "Big Green (Vegan)",
        description: "Vegan doener strips, original Berlin flatbread, lettuce, tomato, cucumber, onions, red cabbage. Sauce: Vegan Garlic.",
        descriptionDE: "Veganes Dönerfleisch im Berliner Fladenbrot, Salat, Tomaten, Gurken, Zwiebeln, Rotkohl. Sauce: Vegane Knoblauchsauce.",
        basePrice: 11.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/big-green.webp",
        badge: "VEGGIE",
        calories: 720,
        allergens: ["Gluten", "Soy", "Sesame"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 4,
      },
    ],
  },

  // 4. MY BOWLS
  {
    id: "cat-bowls",
    slug: "my-bowls",
    name: "My Bowls",
    nameDE: "Döner Fitness & Reis Bowls",
    nameGR: "Μπωλ Ντόνερ",
    description: "Carved rotisserie meat over fragrant white rice or golden crunchy fries, with crisp salads.",
    sortOrder: 4,
    isActive: true,
    products: [
      {
        id: "prod-beef-bowl",
        categoryId: "cat-bowls",
        sku: "MYGD-B1-BF-BOWL",
        name: "Beef Bowl",
        nameDE: "Berliner Rind Bowl",
        nameGR: "Μπωλ Μοσχάρι",
        description: "Beef doener, white rice or crunchy fries, lettuce, tomato, cucumber, red cabbage, onions. Served with your choice of signature sauce.",
        descriptionDE: "Rind-Dönerfleisch mit weißem Reis oder Pommes, Salat, Tomaten, Gurken, Rotkohl, Zwiebeln und Sauce nach Wahl.",
        basePrice: 9.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/doener-bowl.jpg",
        badge: "POPULAR",
        calories: 680,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 1,
      },
      {
        id: "prod-chicken-bowl",
        categoryId: "cat-bowls",
        sku: "MYGD-B1-CK-BOWL",
        name: "Chicken Bowl",
        nameDE: "Hähnchen Döner Bowl",
        nameGR: "Μπωλ Κοτόπουλο",
        description: "Chicken doener, white rice or crunchy fries, lettuce, tomato, cucumber, red cabbage, onions. Served with your choice of signature sauce.",
        descriptionDE: "Hähnchendöner mit weißem Reis oder Pommes, frischem Salat, Tomaten, Gurken, Rotkohl, Zwiebeln und Sauce nach Wahl.",
        basePrice: 9.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/chicken-bowl.webp",
        calories: 620,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 2,
      },
      {
        id: "prod-mix-bowl",
        categoryId: "cat-bowls",
        sku: "MYGD-B1-MIX-BOWL",
        name: "Mix Bowl",
        nameDE: "Mix Döner Bowl (Rind & Huhn)",
        nameGR: "Μιξ Μπωλ (Μοσχάρι & Κοτόπουλο)",
        description: "Beef & chicken doener, white rice or fries, lettuce, tomato, cucumber, red cabbage, onions. Served with your choice of signature sauce.",
        descriptionDE: "Rind & Hähnchendöner mit Reis oder Pommes, Salat, Tomaten, Gurken, Rotkohl, Zwiebeln und Sauce nach Wahl.",
        basePrice: 9.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/mix-bowl.webp",
        calories: 650,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 3,
      },
      {
        id: "prod-vegan-bowl",
        categoryId: "cat-bowls",
        sku: "MYGD-B1-VGN-BOWL",
        name: "Vegan Bowl",
        nameDE: "Vegane Bällchen Bowl",
        nameGR: "Vegan Μπωλ",
        description: "Plant-based vegan balls, white rice or fries, lettuce, tomato, cucumber, red cabbage, onions. Sauce: Vegan Garlic.",
        descriptionDE: "Vegane Bällchen mit weißem Reis oder Pommes, Salat, Tomaten, Gurken, Rotkohl, Zwiebeln. Sauce: Vegane Knoblauchsauce.",
        basePrice: 9.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/vegan-bowl.webp",
        badge: "VEGGIE",
        calories: 520,
        allergens: ["Soy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 4,
      },
    ],
  },

  // 5. MYGD PIZZAS
  {
    id: "cat-pizzas",
    slug: "mygd-pizzas",
    name: "MYGD Pizzas",
    nameDE: "33cm Steinofen Pizzas",
    nameGR: "Πίτσες MYGD",
    description: "Stone-baked thin-crust 33cm pizzas. Buy one, get the second pizza 20% OFF!",
    sortOrder: 5,
    isActive: true,
    products: [
      {
        id: "prod-pizza-margherita",
        categoryId: "cat-pizzas",
        sku: "MYGD-PZ-MARG",
        name: "Margherita Pizza",
        nameDE: "Margherita Steinofen Pizza",
        nameGR: "Πίτσα Μαργαρίτα",
        description: "Italian tomato sauce, 100% mozzarella, fresh tomatoes and herbs.",
        descriptionDE: "Tomatensauce, Mozzarella, frische Tomaten.",
        basePrice: 15.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/pizza-margherita.webp",
        badge: "VEGGIE",
        calories: 820,
        allergens: ["Gluten", "Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 1,
      },
      {
        id: "prod-pizza-salami",
        categoryId: "cat-pizzas",
        sku: "MYGD-PZ-SALAMI",
        name: "Salami Pizza",
        nameDE: "Salami Steinofen Pizza",
        nameGR: "Πίτσα Σαλάμι",
        description: "Rich tomato sauce, melted mozzarella, beef salami, fresh tomatoes.",
        descriptionDE: "Tomatensauce, Mozzarella, Rindersalami, frische Tomaten.",
        basePrice: 16.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/pizza-salami.webp",
        badge: "POPULAR",
        calories: 940,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 2,
      },
      {
        id: "prod-pizza-chicken-doener",
        categoryId: "cat-pizzas",
        sku: "MYGD-PZ-CK-DONER",
        name: "Chicken Doener Pizza",
        nameDE: "Hähnchen Döner Pizza",
        nameGR: "Πίτσα Ντόνερ Κοτόπουλο",
        description: "Tomato sauce, mozzarella, roasted chicken doener, fresh tomatoes, fresh onions, 1 sauce of your choice.",
        descriptionDE: "Tomatensauce, Mozzarella, Hähnchendöner, frische Tomaten, Zwiebeln, 1 Sauce nach Wahl.",
        basePrice: 17.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/chicken-doener-pizza.jpg",
        badge: "BESTSELLER",
        calories: 1020,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 3,
      },
      {
        id: "prod-pizza-funghi",
        categoryId: "cat-pizzas",
        sku: "MYGD-PZ-FUNGHI",
        name: "Funghi Pizza",
        nameDE: "Funghi Steinofen Pizza",
        nameGR: "Πίτσα Μανιτάρια",
        description: "Tomato sauce, mozzarella, fresh mushrooms, fresh tomatoes.",
        descriptionDE: "Tomatensauce, Mozzarella, frische Champignons, frische Tomaten.",
        basePrice: 16.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/pizza-funghi.webp",
        calories: 850,
        allergens: ["Gluten", "Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 4,
      },
      {
        id: "prod-pizza-five-cheese",
        categoryId: "cat-pizzas",
        sku: "MYGD-PZ-5-CHEESE",
        name: "Five Cheese Pizza",
        nameDE: "Fünf Käse Steinofen Pizza",
        nameGR: "Πίτσα Πέντε Τυριά",
        description: "Tomato sauce, mozzarella, gorgonzola, edam, gouda, feta.",
        descriptionDE: "Tomatensauce, Mozzarella, Gorgonzola, Edamer, Gouda, Feta.",
        basePrice: 17.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/pizza-five-cheese.webp",
        badge: "CHEF_CHOICE",
        calories: 990,
        allergens: ["Gluten", "Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 5,
      },
    ],
  },

  // 6. MYGD TACOS
  {
    id: "cat-tacos",
    slug: "mygd-tacos",
    name: "MYGD Tacos",
    nameDE: "MYGD Knusprige Tacos",
    nameGR: "Τάκος MYGD",
    description: "Crispy hard corn taco shells loaded with meat, crisp salad and signature dips. 1 Taco €3.50 | 4 Tacos €11.90!",
    sortOrder: 6,
    isActive: true,
    products: [
      {
        id: "prod-taco-beef",
        categoryId: "cat-tacos",
        sku: "MYGD-TC-BEEF",
        name: "Beef Taco",
        nameDE: "Rindfleisch Taco",
        nameGR: "Τάκο Μοσχάρι",
        description: "Beef, onions, lettuce, cucumber, tomato, red cabbage, BBQ sauce. Single €3.50 or 4 for €11.90.",
        descriptionDE: "Rindfleisch, Zwiebeln, Salat, Gurke, Tomate, Rotkohl, BBQ-Sauce.",
        basePrice: 3.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/beef-taco.jpg",
        badge: "POPULAR",
        calories: 280,
        allergens: [],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 1,
      },
      {
        id: "prod-taco-beef-jalapeno",
        categoryId: "cat-tacos",
        sku: "MYGD-TC-BEEF-JAL",
        name: "Beef Taco with Jalapeños",
        nameDE: "Rindfleisch Taco mit Jalapeños",
        nameGR: "Τάκο Μοσχάρι με Jalapeños",
        description: "Beef, onions, lettuce, cucumber, tomato, red cabbage, spicy jalapeños, sour cream. Single €3.50 or 4 for €11.90.",
        descriptionDE: "Rindfleisch, Zwiebeln, Salat, Gurke, Tomate, Rotkohl, scharfe Jalapeños, Sauerrahm.",
        basePrice: 3.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/taco-beef-jalapeno.webp",
        badge: "SPICY",
        calories: 290,
        allergens: ["Dairy"],
        isSpicy: true,
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 2,
      },
      {
        id: "prod-taco-chicken",
        categoryId: "cat-tacos",
        sku: "MYGD-TC-CHICKEN",
        name: "Chicken Taco",
        nameDE: "Hähnchen Taco",
        nameGR: "Τάκο Κοτόπουλο",
        description: "Chicken, onions, lettuce, cucumber, tomato, red cabbage, garlic sauce. Single €3.50 or 4 for €11.90.",
        descriptionDE: "Hähnchen, Zwiebeln, Salat, Gurke, Tomate, Rotkohl, Knoblauchsauce.",
        basePrice: 3.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/taco-chicken.webp",
        calories: 260,
        allergens: ["Dairy"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 3,
      },
      {
        id: "prod-taco-vegan",
        categoryId: "cat-tacos",
        sku: "MYGD-TC-VEGAN",
        name: "Vegan Taco",
        nameDE: "Veganer Taco",
        nameGR: "Vegan Τάκο",
        description: "Vegan chicken strips, onions, lettuce, cucumber, tomato, red cabbage, vegan garlic sauce. Single €3.50 or 4 for €11.90.",
        descriptionDE: "Vegane Hähnchenstreifen, Zwiebeln, Salat, Gurke, Tomate, Rotkohl, vegane Knoblauchsauce.",
        basePrice: 3.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/taco-vegan.webp",
        badge: "VEGGIE",
        calories: 230,
        allergens: ["Soy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 4,
      },
    ],
  },

  // 7. LOADED FRIES
  {
    id: "cat-loaded-fries",
    slug: "loaded-fries",
    name: "Loaded Fries",
    nameDE: "Loaded Pommes Spezialitäten",
    nameGR: "Loaded Πατάτες",
    description: "Crispy skin-on Berlin fries smothered in rich sauces and toppings. One size, 1 sauce included.",
    sortOrder: 7,
    isActive: true,
    products: [
      {
        id: "prod-loaded-cheesy",
        categoryId: "cat-loaded-fries",
        sku: "MYGD-LF-CHEESY",
        name: "Cheesy Fries",
        nameDE: "Käse Loaded Pommes",
        nameGR: "Πατάτες με Τυρί Cheddar",
        description: "Crispy fries smothered in warm melted cheddar cheese sauce, roasted crispy bits and herbs.",
        descriptionDE: "Knusprige Pommes mit warmer Cheddar-Käsesauce und Kräutern.",
        basePrice: 7.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/cheesy-fries.jpg",
        badge: "BESTSELLER",
        calories: 680,
        allergens: ["Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 1,
      },
      {
        id: "prod-loaded-hollandaise",
        categoryId: "cat-loaded-fries",
        sku: "MYGD-LF-HOLLANDAISE",
        name: "Hollandaise Fries",
        nameDE: "Hollandaise Loaded Pommes",
        nameGR: "Πατάτες Hollandaise",
        description: "Crispy golden fries topped with rich velvety hollandaise sauce and fresh herbs.",
        descriptionDE: "Knusprige Pommes mit reichhaltiger Sauce Hollandaise und Kräutern.",
        basePrice: 7.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/loaded-hollandaise.webp",
        badge: "CHEF_CHOICE",
        calories: 650,
        allergens: ["Dairy", "Egg"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 2,
      },
      {
        id: "prod-loaded-jalapeno",
        categoryId: "cat-loaded-fries",
        sku: "MYGD-LF-JALAPENO",
        name: "Jalapeño Sour Cream Fries",
        nameDE: "Jalapeño Sauerrahm Pommes",
        nameGR: "Πατάτες με Jalapeños & Sour Cream",
        description: "Crispy fries, sliced spicy jalapeño rings, cool sour cream drizzle, spring onions.",
        descriptionDE: "Knusprige Pommes mit Jalapeños, kühler Sauerrahm-Sauce und Frühlingszwiebeln.",
        basePrice: 7.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/loaded-jalapeno.webp",
        badge: "SPICY",
        calories: 590,
        allergens: ["Dairy"],
        isSpicy: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 3,
      },
      {
        id: "prod-loaded-gravy",
        categoryId: "cat-loaded-fries",
        sku: "MYGD-LF-GRAVY",
        name: "Gravy Fries",
        nameDE: "Bratensauce Loaded Pommes",
        nameGR: "Πατάτες με Gravy",
        description: "Double-fried golden fries drenched in rich savory German-style meat gravy sauce.",
        descriptionDE: "Knusprige Pommes mit herzhafter deutscher Bratensauce.",
        basePrice: 7.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/loaded-gravy.webp",
        calories: 580,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 4,
      },
    ],
  },

  // 8. FINGERFOOD & SIDES
  {
    id: "cat-fingerfood",
    slug: "fingerfood-sides",
    name: "Fingerfood & Sides",
    nameDE: "Fingerfood & Beilagen",
    nameGR: "Fingerfood & Συνοδευτικά",
    description: "Crispy sides, mozzarella sticks, onion rings, nuggets and wings.",
    sortOrder: 8,
    isActive: true,
    products: [
      {
        id: "prod-meatballs",
        categoryId: "cat-fingerfood",
        sku: "MYGD-FF-MEATBALLS",
        name: "Meatballs (with Fries or Rice)",
        nameDE: "Fleischbällchen mit Pommes oder Reis",
        nameGR: "Κεφτεδάκια με Πατάτες ή Ρύζι",
        description: "Juicy spiced meatballs served with fries or white rice, 1 sauce included. 6 Pcs €7.50 / 12 Pcs €11.50 / 20 Pcs €16.50.",
        descriptionDE: "Würzige Fleischbällchen mit Pommes oder Reis, inkl. 1 Sauce.",
        basePrice: 7.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/meatballs.webp",
        badge: "POPULAR",
        calories: 620,
        allergens: ["Gluten", "Egg"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 1,
      },
      {
        id: "prod-mozzarella-sticks",
        categoryId: "cat-fingerfood",
        sku: "MYGD-FF-MOZZ-STICKS",
        name: "Mozzarella Sticks",
        nameDE: "Mozzarella Sticks",
        nameGR: "Μοτσαρέλα Στικς",
        description: "Golden breaded mozzarella with stretchy melted cheese core, 1 sauce included. 6 Pcs €5.90 / 12 Pcs €9.90 / 20 Pcs €14.90.",
        descriptionDE: "Knusprig panierte Mozzarella Sticks, inkl. 1 Sauce.",
        basePrice: 5.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/mozzarella-sticks.webp",
        badge: "POPULAR",
        calories: 510,
        allergens: ["Gluten", "Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 2,
      },
      {
        id: "prod-onion-rings",
        categoryId: "cat-fingerfood",
        sku: "MYGD-FF-ONION-RINGS",
        name: "Onion Rings",
        nameDE: "Zwiebelringe im Bierteig",
        nameGR: "Ροδέλες Κρεμμυδιού",
        description: "Crispy beer-battered sweet onion rings, 1 sauce included. 6 Pcs €1.95 / 12 Pcs €3.50 / 20 Pcs €5.50.",
        descriptionDE: "Knusprige Zwiebelringe, inkl. 1 Sauce.",
        basePrice: 1.95,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/onion-rings.webp",
        calories: 380,
        allergens: ["Gluten"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 3,
      },
      {
        id: "prod-chicken-nuggets",
        categoryId: "cat-fingerfood",
        sku: "MYGD-FF-NUGGETS",
        name: "Chicken Nuggets",
        nameDE: "Knusprige Hähnchen Nuggets",
        nameGR: "Κοτομπουκιές",
        description: "100% crispy chicken breast bites with dipping sauces. 6 Pcs €4.90 (1 sauce) / 12 Pcs €7.90 (2 sauces) / 20 Pcs €11.90 (3 sauces).",
        descriptionDE: "Knusprige Chicken Nuggets aus Hähnchenbrustfilet.",
        basePrice: 4.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/chicken-nuggets.webp",
        badge: "BESTSELLER",
        calories: 450,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 4,
      },
      {
        id: "prod-chicken-wings",
        categoryId: "cat-fingerfood",
        sku: "MYGD-FF-WINGS",
        name: "Chicken Wings",
        nameDE: "Knusprige Chicken Wings",
        nameGR: "Φτερούγες Κοτόπουλου",
        description: "Crispy spiced chicken wings. 6 Pcs €5.90 (1 sauce) / 12 Pcs €9.90 (2 sauces) / 20 Pcs €14.90 (3 sauces).",
        descriptionDE: "Würzige Chicken Wings mit Dip.",
        basePrice: 5.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/chicken-wings.webp",
        badge: "SPICY",
        calories: 520,
        allergens: [],
        isSpicy: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 5,
      },
      {
        id: "prod-crunchy-fries",
        categoryId: "cat-fingerfood",
        sku: "MYGD-FF-CRUNCHY-FRIES",
        name: "Crunchy Fries",
        nameDE: "Knusprige Pommes",
        nameGR: "Τραγανές Πατάτες",
        description: "Skin-on golden fries with German paprika sea salt seasoning. Regular €2.50 (1 sauce) / Large €3.50 (2 sauces) / XL €4.50 (2 sauces).",
        descriptionDE: "Knusprige Pommes Frites mit Paprika-Gewürz.",
        basePrice: 2.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/crunchy-fries.webp",
        calories: 340,
        allergens: [],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 6,
      },
      {
        id: "prod-sweet-potato-fries",
        categoryId: "cat-fingerfood",
        sku: "MYGD-FF-SWEET-FRIES",
        name: "Sweet Potato Fries",
        nameDE: "Süßkartoffel Pommes",
        nameGR: "Γλυκοπατάτες",
        description: "Crispy sweet potato fries. Regular €2.90 (1 sauce) / Large €3.90 (2 sauces) / XL €4.90 (2 sauces).",
        descriptionDE: "Knusprige Süßkartoffel Pommes mit Dip.",
        basePrice: 2.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/sweet-potato-fries.webp",
        badge: "CHEF_CHOICE",
        calories: 360,
        allergens: [],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 7,
      },
      {
        id: "prod-kids-meal",
        categoryId: "cat-fingerfood",
        sku: "MYGD-FF-KIDS-MEAL",
        name: "Kids Meal Box",
        nameDE: "MYGD Kinder Menü Box",
        nameGR: "Παιδικό Γεύμα Box",
        description: "Choose Main: Kids Doener OR 4 Chicken Nuggets OR 4 Meatballs with Hollandaise. Includes Small Fries + Drink Choice (Water / Ayran / Cappy Juice) + 1 Kinder Riegel chocolate bar.",
        descriptionDE: "Kinder Döner, 4 Nuggets oder 4 Fleischbällchen + kleine Pommes + Getränk + 1 Kinder Riegel.",
        basePrice: 5.00,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/kids-meal.webp",
        badge: "TOP_SELLER",
        calories: 580,
        allergens: ["Gluten", "Dairy", "Egg"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 8,
      },
    ],
  },

  // 9. FRESH SALADS
  {
    id: "cat-salads",
    slug: "fresh-salads",
    name: "Fresh Salads",
    nameDE: "Frische Salate",
    nameGR: "Φρέσκες Σαλάτες",
    description: "Crisp garden salads prepared daily with vinaigrette dressing.",
    sortOrder: 9,
    isActive: true,
    products: [
      {
        id: "prod-salad-garden",
        categoryId: "cat-salads",
        sku: "MYGD-SL-GARDEN",
        name: "Garden Salad",
        nameDE: "Gartensalat",
        nameGR: "Σαλάτα του Κήπου",
        description: "Lettuce, cucumber, tomato, red cabbage, onion with vinegar & oil dressing.",
        descriptionDE: "Blattsalat, Gurken, Tomaten, Rotkohl, Zwiebeln mit Essig & Öl Dressing.",
        basePrice: 6.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/salad-garden.webp",
        badge: "VEGGIE",
        calories: 210,
        allergens: [],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 1,
      },
      {
        id: "prod-salad-chicken",
        categoryId: "cat-salads",
        sku: "MYGD-SL-CHICKEN",
        name: "Chicken Salad",
        nameDE: "Hähnchen Salat",
        nameGR: "Σαλάτα Κοτόπουλο",
        description: "Garden salad topped with tender carved rotisserie chicken doener, with vinegar & oil dressing.",
        descriptionDE: "Gartensalat mit zartem Hähnchendönerfleisch und Essig & Öl Dressing.",
        basePrice: 8.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/salad-chicken.webp",
        badge: "POPULAR",
        calories: 420,
        allergens: [],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 2,
      },
      {
        id: "prod-salad-halloumi",
        categoryId: "cat-salads",
        sku: "MYGD-SL-HALLOUMI",
        name: "Halloumi Salad",
        nameDE: "Halloumi Salat",
        nameGR: "Σαλάτα Χαλούμι",
        description: "Garden salad topped with warm grilled Cyprus halloumi cheese slices and herb vinaigrette.",
        descriptionDE: "Gartensalat mit gegrilltem zypriotischem Halloumi und Essig & Öl Dressing.",
        basePrice: 8.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/salad-halloumi.webp",
        badge: "CHEF_CHOICE",
        calories: 480,
        allergens: ["Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 3,
      },
    ],
  },

  // 10. DRINKS & BEVERAGES
  {
    id: "cat-drinks",
    slug: "drinks",
    name: "Drinks & Beverages",
    nameDE: "Getränke & Biere",
    nameGR: "Ποτά & Αναψυκτικά",
    description: "Imported German beers, wines, fresh smoothies, milkshakes, soft drinks and roasted espresso.",
    sortOrder: 10,
    isActive: true,
    products: [
      {
        id: "prod-beer-hb-draft-500",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-HB-DFT-500",
        name: "Hofbräu München Draft (0.5L)",
        nameDE: "Hofbräu München Frischgezapft (0.5L)",
        nameGR: "Hofbräu Βαρελίσια (0.5L)",
        description: "Imported Munich Bavarian pale lager from the tap with crisp malt & herbal hop balance.",
        basePrice: 6.00,
        vatCategory: "ALCOHOL",
        imageUrl: "/assets/menu/products/drink-draft-beer.webp",
        badge: "POPULAR",
        calories: 210,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 1,
      },
      {
        id: "prod-beer-hb-draft-300",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-HB-DFT-300",
        name: "Hofbräu München Draft (0.3L)",
        nameDE: "Hofbräu München Frischgezapft (0.3L)",
        nameGR: "Hofbräu Βαρελίσια (0.3L)",
        description: "Freshly poured Bavarian draft beer 0.3L.",
        basePrice: 4.00,
        vatCategory: "ALCOHOL",
        imageUrl: "/assets/menu/products/drink-draft-beer.webp",
        calories: 130,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 2,
      },
      {
        id: "prod-beer-hb-bottle",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-HB-BTL-500",
        name: "Hofbräu Original / Helles Bottle (0.5L)",
        nameDE: "Hofbräu Original / Helles Flasche (0.5L)",
        nameGR: "Hofbräu Μπουκάλι (0.5L)",
        description: "Classic Munich bottled lager 500ml.",
        basePrice: 5.00,
        vatCategory: "ALCOHOL",
        imageUrl: "/assets/menu/products/drink-bottled-beer.webp",
        calories: 220,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 3,
      },
      {
        id: "prod-beer-corona",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-CORONA-330",
        name: "Corona Extra / 0.0% (330ml)",
        nameDE: "Corona Extra / Alkoholfrei (330ml)",
        nameGR: "Corona Extra / 0.0% (330ml)",
        description: "Chilled Mexican lager served with fresh lime wedge.",
        basePrice: 4.00,
        vatCategory: "ALCOHOL",
        imageUrl: "/assets/menu/products/drink-bottled-beer.webp",
        calories: 140,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 4,
      },
      {
        id: "prod-beer-keo-carlsberg",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-KEO-CARLS",
        name: "KEO / Carlsberg / Carlsberg 0.0% (330ml)",
        nameDE: "KEO / Carlsberg / Alkoholfrei (330ml)",
        nameGR: "KEO / Carlsberg (330ml)",
        description: "Chilled Cyprus or European pilsner.",
        basePrice: 3.00,
        vatCategory: "ALCOHOL",
        imageUrl: "/assets/menu/products/drink-bottled-beer.webp",
        calories: 135,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 5,
      },
      {
        id: "prod-wine-glass",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-WINE-GLS",
        name: "Wine Glass (Red / White)",
        nameDE: "Hauswein Glas (Rot / Weiß)",
        nameGR: "Ποτήρι Κρασί (Κόκκινο / Λευκό)",
        description: "Glass of house red or white wine.",
        basePrice: 4.00,
        vatCategory: "ALCOHOL",
        imageUrl: "/assets/menu/products/drink-wine.webp",
        calories: 125,
        allergens: [],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 6,
      },
      {
        id: "prod-soda-postmix",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-SODA-PM-400",
        name: "Soft Drink Postmix (0.4L)",
        nameDE: "Softdrink Frischgezapft (0.4L)",
        nameGR: "Αναψυκτικό Postmix (0.4L)",
        description: "Coca-Cola, Coca-Cola Zero, Fanta Zero, Sprite, Sprite Zero, or Sparkling Water poured over crushed ice.",
        basePrice: 2.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/drink-postmix-soda.webp",
        calories: 150,
        allergens: [],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 7,
      },
      {
        id: "prod-canned-drinks",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-CAN-330",
        name: "Canned Drinks (330ml)",
        nameDE: "Dosengetränke (330ml)",
        nameGR: "Αναψυκτικά σε Κουτάκι (330ml)",
        description: "Fanta Lemon, Fanta Zero, Lipton Ice Tea Peach, Peach Zero, or Ice Tea Lemon.",
        basePrice: 2.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/drink-canned-soda.webp",
        calories: 110,
        allergens: [],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 8,
      },
      {
        id: "prod-ayran-500",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-AYRAN-500",
        name: "Authentic Chilled Ayran (0.5L)",
        nameDE: "Traditioneller Ayran (0.5L)",
        nameGR: "Παραδοσιακό Αριάνι (0.5L)",
        description: "Traditional chilled Turkish yogurt, sea salt & pure water beverage.",
        basePrice: 3.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/water-ayran.webp",
        badge: "BESTSELLER",
        calories: 160,
        allergens: ["Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 9,
      },
      {
        id: "prod-water-kykkos",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-WATER-500",
        name: "Kykkos Still Mineral Water (0.5L)",
        nameDE: "Kykkos Mineralwasser Still (0.5L)",
        nameGR: "Κύκκος Φυσικό Νερό (0.5L)",
        description: "Pure natural mountain mineral water.",
        basePrice: 1.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/water-ayran.webp",
        calories: 0,
        allergens: [],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 10,
      },
      {
        id: "prod-smoothie-all",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-SMOOTHIE",
        name: "Fruit Smoothies (0.4L)",
        nameDE: "Frische Frucht-Smoothies (0.4L)",
        nameGR: "Smoothies Φρούτων (0.4L)",
        description: "100% natural pure fruit blends: Tropical Twist, Berry Booster, Green Power, or Sunset Delight.",
        basePrice: 2.99,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/smoothies-blend.webp",
        badge: "POPULAR",
        calories: 190,
        allergens: [],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 11,
      },
      {
        id: "prod-milkshake-all",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-MILKSHAKE",
        name: "Rich Milkshakes (0.4L)",
        nameDE: "Milchshakes (0.4L)",
        nameGR: "Milkshakes (0.4L)",
        description: "Hand-spun rich ice cream shake: Strawberry, Vanilla, or Chocolate.",
        basePrice: 2.90,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/milkshakes-trio.webp",
        calories: 380,
        allergens: ["Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 12,
      },
      {
        id: "prod-red-bull",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-REDBULL-250",
        name: "Red Bull Energy Drink (250ml)",
        nameDE: "Red Bull Energy Drink (250ml)",
        nameGR: "Red Bull (250ml)",
        description: "Classic Red Bull or Sugarfree.",
        basePrice: 3.00,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/red-bull.webp",
        calories: 115,
        allergens: [],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 13,
      },
      {
        id: "prod-kombucha-gaia",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-KOMBUCHA-330",
        name: "Gaia Organic Kombucha (330ml)",
        nameDE: "Gaia Bio-Kombucha (330ml)",
        nameGR: "Gaia Kombucha (330ml)",
        description: "Naturally fermented sparkling tea: Hibiscus, Lemon Zen, Ginger Insight, or Lemongrass Unity.",
        basePrice: 3.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/kombucha-gaia.webp",
        calories: 60,
        allergens: [],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 14,
      },
      {
        id: "prod-coffee-cappuccino",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-COF-CAPPUCCINO",
        name: "Cappuccino Italiano / Latte",
        nameDE: "Italienischer Cappuccino / Latte",
        nameGR: "Καπουτσίνο / Λάτε",
        description: "Freshly ground double espresso shot with micro-foamed milk.",
        basePrice: 3.00,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/coffee-cappuccino.webp",
        calories: 110,
        allergens: ["Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 15,
      },
      {
        id: "prod-coffee-espresso",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-COF-ESPRESSO",
        name: "Espresso Roast / Americano",
        nameDE: "Espresso / Americano",
        nameGR: "Εσπρέσο / Αμερικάνο",
        description: "Rich Italian single espresso (€2.00) or Americano (€2.50).",
        basePrice: 2.00,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/coffee-espresso.webp",
        calories: 5,
        allergens: [],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 16,
      },
    ],
  },

  // 11. COMING SOON: DOEZZA & BURGERS
  {
    id: "cat-coming-soon",
    slug: "coming-soon",
    name: "Coming Soon: Doezza & Burgers",
    nameDE: "Bald Verfügbar: Doezza & Burger",
    nameGR: "Σύντομα: Doezza & Burgers",
    description: "Our upcoming street food innovations: Turkish flatbread Doezza slices and gourmet smash burgers.",
    sortOrder: 11,
    isActive: true,
    products: [
      {
        id: "prod-doezza-margherita",
        categoryId: "cat-coming-soon",
        sku: "MYGD-DZ-MARG",
        name: "Doezza Margherita Slice",
        nameDE: "Doezza Margherita Dreieck",
        nameGR: "Doezza Μαργαρίτα",
        description: "Triangular crispy flatbread slice with tomato sauce & melted cheese.",
        basePrice: 6.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/doezza-margherita.webp",
        calories: 320,
        allergens: ["Gluten", "Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 1,
      },
      {
        id: "prod-doezza-salami",
        categoryId: "cat-coming-soon",
        sku: "MYGD-DZ-SALAMI",
        name: "Doezza Salami Slice",
        nameDE: "Doezza Salami Dreieck",
        nameGR: "Doezza Σαλάμι",
        description: "Crispy triangular flatbread slice with beef salami & cheese.",
        basePrice: 7.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/doezza-salami.webp",
        calories: 380,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 2,
      },
      {
        id: "prod-doezza-funghi",
        categoryId: "cat-coming-soon",
        sku: "MYGD-DZ-FUNGHI",
        name: "Doezza Funghi Slice",
        nameDE: "Doezza Funghi Dreieck",
        nameGR: "Doezza Μανιτάρια",
        description: "Flatbread slice with mushrooms & cheese.",
        basePrice: 6.95,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/doezza-funghi.webp",
        calories: 310,
        allergens: ["Gluten", "Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 3,
      },
      {
        id: "prod-doezza-four-cheese",
        categoryId: "cat-coming-soon",
        sku: "MYGD-DZ-4-CHEESE",
        name: "Doezza Four Cheese Slice",
        nameDE: "Doezza Vier Käse Dreieck",
        nameGR: "Doezza Τέσσερα Τυριά",
        description: "Crispy flatbread slice with four premium melted cheeses.",
        basePrice: 7.95,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/doezza-four-cheese.webp",
        badge: "CHEF_CHOICE",
        calories: 390,
        allergens: ["Gluten", "Dairy"],
        isVeggie: true,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 4,
      },
      {
        id: "prod-burger-beefster",
        categoryId: "cat-coming-soon",
        sku: "MYGD-BG-BEEFSTER",
        name: "Beefster Burger",
        nameDE: "Beefster Döner Burger",
        nameGR: "Beefster Burger",
        description: "Rotisserie beef, melted cheddar cheese, crisp lettuce, tomato, signature cocktail sauce in toasted bun.",
        basePrice: 7.95,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/burger-beefster.webp",
        badge: "BESTSELLER",
        calories: 610,
        allergens: ["Gluten", "Dairy", "Egg"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 5,
      },
      {
        id: "prod-burger-cheesy-gd",
        categoryId: "cat-coming-soon",
        sku: "MYGD-BG-CHEESY-GD",
        name: "Cheesy GD Burger",
        nameDE: "Cheesy GD Doppelkäse Burger",
        nameGR: "Cheesy GD Burger",
        description: "Double döner beef, double cheddar cheese, garlic herb sauce.",
        basePrice: 9.95,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/burger-cheesy-gd.webp",
        badge: "POPULAR",
        calories: 780,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 6,
      },
      {
        id: "prod-burger-chicken-hype",
        categoryId: "cat-coming-soon",
        sku: "MYGD-BG-CK-HYPE",
        name: "Chicken Hype Burger",
        nameDE: "Chicken Hype Burger",
        nameGR: "Chicken Hype Burger",
        description: "Crispy chicken döner strips, special herb cream sauce.",
        basePrice: 8.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/burger-chicken-hype.webp",
        calories: 590,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 7,
      },
      {
        id: "prod-burger-cc-chicken",
        categoryId: "cat-coming-soon",
        sku: "MYGD-BG-CC-CHICKEN",
        name: "C & C Chicken Burger",
        nameDE: "Crispy & Cheesy Chicken Burger",
        nameGR: "Crispy & Cheesy Chicken Burger",
        description: "Crispy chicken patty with melted cheddar, fresh lettuce, mayo.",
        basePrice: 7.95,
        vatCategory: "FOOD_BEV",
        imageUrl: "/assets/menu/products/burger-cc-chicken.webp",
        calories: 580,
        allergens: ["Gluten", "Dairy", "Egg"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 8,
      },
    ],
  },
];
