// MY GERMAN DÖNER — Master Catalog Data & Asset Intelligence Vault
// Source of truth matching https://mygermandoener.com/ (Shopify ID: 96390807899)
// Provides 100% offline resilience and high-res imagery for Public Web, POS, Kiosks & 4K Signage.

export interface MasterCatalogProduct {
  id: string;
  categoryId: string;
  sku: string;
  name: string;
  nameDE?: string;
  nameGR?: string;
  description: string;
  descriptionDE?: string;
  descriptionGR?: string;
  basePrice: number;
  vatCategory: "FOOD_BEV" | "ALCOHOL" | "ZERO";
  imageUrl: string;
  badge?: string;
  calories?: number;
  allergens?: string[];
  isVeggie?: boolean;
  isSpicy?: boolean;
  isAvailable: boolean;
  allowMealUpgrade: boolean;
  sortOrder: number;
}

export interface MasterCatalogCategory {
  id: string;
  slug: string;
  name: string;
  nameDE: string;
  nameGR: string;
  description?: string;
  sortOrder: number;
  isActive: boolean;
  products: MasterCatalogProduct[];
}

export const CANONICAL_CATALOG_CATEGORIES: MasterCatalogCategory[] = [
  {
    id: "cat-doner",
    slug: "doner-kebab",
    name: "Original Döner Kebab",
    nameDE: "Klassischer Berliner Döner",
    nameGR: "Κλασικό Ντόνερ Κεμπάπ",
    description: "Authentic Berlin rotisserie meat in fresh toasted sesame Turkish bread.",
    sortOrder: 1,
    isActive: true,
    products: [
      {
        id: "prod-doner-beef",
        categoryId: "cat-doner",
        sku: "MYGD-DONER-BEEF",
        name: "Original Beef & Lamb Döner (150g)",
        nameDE: "Original Berliner Rind & Lamm Döner (150g)",
        nameGR: "Κλασικό Ντόνερ Μοσχάρι & Αρνί (150g)",
        description: "Thinly shaved rotisserie beef & lamb, crisp red cabbage, fresh lettuce, tomatoes & homemade garlic/herb sauces in toasted sesame flatbread.",
        basePrice: 10.00,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=1200&auto=format&fit=crop&q=85",
        badge: "POPULAR",
        calories: 720,
        allergens: ["Gluten", "Dairy", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 1,
      },
      {
        id: "prod-doner-chicken",
        categoryId: "cat-doner",
        sku: "MYGD-DONER-CHICKEN",
        name: "Crispy Chicken Döner (150g)",
        nameDE: "Knuspriger Hähnchen Döner (150g)",
        nameGR: "Ντόνερ Κοτόπουλο (150g)",
        description: "Juicy marinated chicken rotisserie, fresh herbs, crisp iceberg lettuce, tomatoes & Kräuter garlic yogurt sauce.",
        basePrice: 9.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=1200&auto=format&fit=crop&q=85",
        badge: "BESTSELLER",
        calories: 650,
        allergens: ["Gluten", "Dairy", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 2,
      },
      {
        id: "prod-doner-steak",
        categoryId: "cat-doner",
        sku: "MYGD-DONER-STEAK",
        name: "Steak Döner (100% Beef 150g)",
        nameDE: "100% Rinder-Steak Döner (150g)",
        nameGR: "Στέικ Ντόνερ 100% Μοσχάρι (150g)",
        description: "Premium pure beef steak slices carved hot from the spit with fresh rosemary, parsley & lemon garlic cream.",
        basePrice: 12.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&auto=format&fit=crop&q=85",
        badge: "CHEF_CHOICE",
        calories: 780,
        allergens: ["Gluten", "Dairy", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 3,
      },
      {
        id: "prod-doner-veggie-chicken",
        categoryId: "cat-doner",
        sku: "MYGD-DONER-VEGGIE-CHICKEN",
        name: "Plant-Based Veggie Chicken Döner (150g)",
        nameDE: "Veggie Chicken Döner (100% Vegan)",
        nameGR: "Χορτοφαγικό Ντόνερ Κοτόπουλο (150g)",
        description: "100% plant-based spiced döner strips roasted with fresh peppers, onions, crisp lettuce & vegan tahini sauce.",
        basePrice: 9.50,
        vatCategory: "FOOD_BEV",
        isVeggie: true,
        imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1200&auto=format&fit=crop&q=85",
        badge: "VEGGIE",
        calories: 540,
        allergens: ["Gluten", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 4,
      },
    ],
  },
  {
    id: "cat-wraps",
    slug: "durum-wraps",
    name: "Dürüm Wraps",
    nameDE: "Berliner Dürüm Wraps",
    nameGR: "Τυλιχτά Dürüm",
    description: "Rolled in warm toasted lavash flatbread with Mediterranean greens & homemade sauces.",
    sortOrder: 2,
    isActive: true,
    products: [
      {
        id: "prod-wrap-beef",
        categoryId: "cat-wraps",
        sku: "MYGD-WRAP-BEEF",
        name: "Beef & Lamb Dürüm Wrap (150g)",
        nameDE: "Rind & Lamm Dürüm Wrap (150g)",
        nameGR: "Dürüm Μοσχάρι & Αρνί (150g)",
        description: "Toasted lavash flatbread rolled with sliced beef & lamb, pickled cabbage, onions & spicy chili sauce.",
        basePrice: 10.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=1200&auto=format&fit=crop&q=85",
        badge: "POPULAR",
        calories: 680,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 5,
      },
      {
        id: "prod-wrap-halloumi",
        categoryId: "cat-wraps",
        sku: "MYGD-WRAP-HALLOUMI",
        name: "Cyprus Grilled Halloumi Dürüm",
        nameDE: "Gegrillter Halloumi Dürüm",
        nameGR: "Dürüm με Κυπριακό Χαλλούμι",
        description: "Thick slices of authentic Cyprus halloumi grilled golden, wrapped with fresh tomatoes, cucumber, mint & garlic yogurt dip.",
        basePrice: 8.00,
        vatCategory: "FOOD_BEV",
        isVeggie: true,
        imageUrl: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=1200&auto=format&fit=crop&q=85",
        badge: "VEGGIE",
        calories: 590,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 6,
      },
      {
        id: "prod-wrap-falafel",
        categoryId: "cat-wraps",
        sku: "MYGD-WRAP-FALAFEL",
        name: "Crispy Fresh Falafel Wrap",
        nameDE: "Frischer Falafel Dürüm",
        nameGR: "Dürüm με Φρέσκο Φαλάφελ",
        description: "Golden fried chickpea falafels with creamy hummus, tahini, parsley salad & pickled red onions.",
        basePrice: 8.00,
        vatCategory: "FOOD_BEV",
        isVeggie: true,
        imageUrl: "https://images.unsplash.com/photo-1593504049359-74330189a345?w=1200&auto=format&fit=crop&q=85",
        badge: "VEGGIE",
        calories: 530,
        allergens: ["Gluten", "Sesame"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 7,
      },
    ],
  },
  {
    id: "cat-bowls",
    slug: "doner-bowls",
    name: "Bowls & Boxes",
    nameDE: "Döner Boxen & Fitness Bowls",
    nameGR: "Μπολ & Κουτιά Ντόνερ",
    description: "High-protein bowls served with steamed rice, crispy fries, and fresh garden salad.",
    sortOrder: 3,
    isActive: true,
    products: [
      {
        id: "prod-box-crisp",
        categoryId: "cat-bowls",
        sku: "MYGD-BOX-CRISP",
        name: "Berlin Döner Box with Fries",
        nameDE: "Berliner Döner Box mit Pommes",
        nameGR: "Κουτί Ντόνερ με Πατάτες",
        description: "Crispy skin-on fries topped with shaved rotisserie meat, creamy garlic sauce & spicy herbs in a handy to-go box.",
        basePrice: 8.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=1200&auto=format&fit=crop&q=85",
        badge: "BESTSELLER",
        calories: 740,
        allergens: ["Dairy"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 8,
      },
      {
        id: "prod-bowl-fitness",
        categoryId: "cat-bowls",
        sku: "MYGD-BOWL-FITNESS",
        name: "Low-Carb Döner Fitness Bowl (150g)",
        nameDE: "Low-Carb Fitness Döner Bowl (150g)",
        nameGR: "Fitness Μπολ Ντόνερ (150g)",
        description: "Generous portion of rotisserie meat over steamed basmati rice, Mediterranean chopped salad, feta cheese & herb dressing.",
        basePrice: 11.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&auto=format&fit=crop&q=85",
        badge: "CHEF_CHOICE",
        calories: 610,
        allergens: ["Dairy"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 9,
      },
    ],
  },
  {
    id: "cat-pizza-burgers",
    slug: "pizza-burgers",
    name: "Pizzas & Burgers",
    nameDE: "33cm Döner-Pizza & Burger",
    nameGR: "Πίτσες & Μπέργκερ Ντόνερ",
    description: "Stone-baked 33cm pizzas and juicy döner burgers in toasted brioche buns.",
    sortOrder: 4,
    isActive: true,
    products: [
      {
        id: "prod-pizza-chicken",
        categoryId: "cat-pizza-burgers",
        sku: "MYGD-PIZZA-CHICKEN",
        name: "33cm Stone-Baked Chicken Döner Pizza",
        nameDE: "33cm Steinofen Döner-Pizza Hähnchen",
        nameGR: "Πίτσα Ντόνερ Κοτόπουλο 33cm",
        description: "Crispy thin crust topped with Italian tomato sauce, mozzarella, shaved chicken döner, sliced onions & garlic drizzle.",
        basePrice: 14.00,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&auto=format&fit=crop&q=85",
        badge: "POPULAR",
        calories: 1050,
        allergens: ["Gluten", "Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 10,
      },
      {
        id: "prod-burger-steak",
        categoryId: "cat-pizza-burgers",
        sku: "MYGD-BURGER-STEAK",
        name: "Steak Döner Burger in Brioche",
        nameDE: "Rinder-Steak Döner Burger",
        nameGR: "Μπέργκερ Στέικ Ντόνερ σε Brioche",
        description: "Juicy beef steak döner slices packed in toasted brioche bun with cheddar cheese, lettuce, tomato & cocktail burger sauce.",
        basePrice: 8.50,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&auto=format&fit=crop&q=85",
        badge: "NEW",
        calories: 690,
        allergens: ["Gluten", "Dairy", "Egg"],
        isAvailable: true,
        allowMealUpgrade: true,
        sortOrder: 11,
      },
    ],
  },
  {
    id: "cat-sides",
    slug: "sides-fries",
    name: "Sides & Loaded Fries",
    nameDE: "Beilagen & Pommes Spezialitäten",
    nameGR: "Συνοδευτικά & Πατάτες",
    description: "Crispy double-fried Berlin Pommes and loaded cheese fries.",
    sortOrder: 5,
    isActive: true,
    products: [
      {
        id: "prod-fries-large",
        categoryId: "cat-sides",
        sku: "MYGD-FRIES-LARGE",
        name: "Crispy Berlin Pommes (Large)",
        nameDE: "Knusprige Berliner Pommes (Groß)",
        nameGR: "Τραγανές Πατάτες Βερολίνου (Μεγάλες)",
        description: "Double-fried golden crispy french fries seasoned with German paprika salt.",
        basePrice: 4.50,
        vatCategory: "FOOD_BEV",
        isVeggie: true,
        imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=1200&auto=format&fit=crop&q=85",
        calories: 480,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 12,
      },
      {
        id: "prod-fr-truffle",
        categoryId: "cat-sides",
        sku: "MYGD-FR-TRUFFLE",
        name: "Truffle Parmesan Loaded Fries",
        nameDE: "Trüffel Parmesan Pommes",
        nameGR: "Πατάτες με Τρούφα & Παρμεζάνα",
        description: "Crispy fries drizzled with black truffle mayo, shaved aged parmesan & fresh chopped parsley.",
        basePrice: 8.50,
        vatCategory: "FOOD_BEV",
        isVeggie: true,
        imageUrl: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=1200&auto=format&fit=crop&q=85",
        badge: "NEW",
        calories: 560,
        allergens: ["Dairy", "Egg"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 13,
      },
      {
        id: "prod-fr-chili-cheese",
        categoryId: "cat-sides",
        sku: "MYGD-FR-CHILI-CHEESE",
        name: "Chili-Cheese Loaded Fries",
        nameDE: "Chili-Cheese Pommes",
        nameGR: "Πατάτες Chili-Cheese",
        description: "Hot crispy fries smothered in melted cheddar cheese sauce and sliced spicy pickled jalapeños.",
        basePrice: 6.50,
        vatCategory: "FOOD_BEV",
        isSpicy: true,
        isVeggie: true,
        imageUrl: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=1200&auto=format&fit=crop&q=85",
        badge: "SPICY",
        calories: 620,
        allergens: ["Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 14,
      },
    ],
  },
  {
    id: "cat-drinks",
    slug: "drinks",
    name: "Drinks, Ayran & Beer",
    nameDE: "Getränke, Ayran & Deutsches Bier",
    nameGR: "Ποτά, Αϊράνι & Μπύρες",
    description: "Ice cold authentic Ayran, soft drinks, and imported German draft beer.",
    sortOrder: 6,
    isActive: true,
    products: [
      {
        id: "prod-dr-ayran",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-AYRAN",
        name: "Original Chilled Ayran (250ml)",
        nameDE: "Original Gekühlter Ayran (250ml)",
        nameGR: "Αυθεντικό Αϊράνι (250ml)",
        description: "Traditional salted Turkish yogurt drink served ice cold.",
        basePrice: 2.20,
        vatCategory: "FOOD_BEV",
        isVeggie: true,
        imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=85",
        calories: 95,
        allergens: ["Dairy"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 15,
      },
      {
        id: "prod-dr-cola",
        categoryId: "cat-drinks",
        sku: "MYGD-DR-COLA",
        name: "Coca-Cola Original (330ml Can)",
        nameDE: "Coca-Cola Classic (330ml Dose)",
        nameGR: "Coca-Cola (330ml)",
        description: "Ice cold original Coca-Cola can.",
        basePrice: 2.00,
        vatCategory: "FOOD_BEV",
        isVeggie: true,
        imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&auto=format&fit=crop&q=85",
        calories: 139,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 16,
      },
      {
        id: "prod-alc-beer",
        categoryId: "cat-drinks",
        sku: "MYGD-ALC-BEER",
        name: "German Premium Pilsner (330ml Bottle)",
        nameDE: "Deutsches Premium Pilsner (330ml)",
        nameGR: "Γερμανική Μπύρα Pilsner (330ml)",
        description: "Crisp German draft lager bottle (5.0% ABV, 19% Cyprus Standard VAT).",
        basePrice: 3.50,
        vatCategory: "ALCOHOL",
        imageUrl: "https://images.unsplash.com/photo-1608270199144-8cb38a0f51e0?w=800&auto=format&fit=crop&q=85",
        calories: 145,
        allergens: ["Gluten"],
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 17,
      },
    ],
  },
  {
    id: "cat-combos",
    slug: "meal-combos",
    name: "Meal Combos & Deals",
    nameDE: "Menü-Angebote & Spardeals",
    nameGR: "Οικονομικά Μενού & Προσφορές",
    description: "Best-value combo bundles with fries and drinks.",
    sortOrder: 7,
    isActive: true,
    products: [
      {
        id: "prod-combo-mymeal",
        categoryId: "cat-combos",
        sku: "MYGD-COMBO-MYMEAL",
        name: "MY-MEAL Combo Bundle (€15.00)",
        nameDE: "MY-MEAL Sparmenü Bundle (€15.00)",
        nameGR: "MY-MEAL Ολοκληρωμένο Μενού (€15.00)",
        description: "Any Standard Döner (150g) + Crispy Berlin Fries + Chilled 330ml Drink. Save €2.00!",
        basePrice: 15.00,
        vatCategory: "FOOD_BEV",
        imageUrl: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=1200&auto=format&fit=crop&q=85",
        badge: "POPULAR",
        calories: 1250,
        isAvailable: true,
        allowMealUpgrade: false,
        sortOrder: 18,
      },
    ],
  },
];
