// MY GERMAN DÖNER — 4K Dynamic Menu Board Engine
import { SignageScreenConfig } from "./signage.schema";

// TODO(phase-6): HARD-CODED MOCK DATA — these products and prices are not read from the database.
// Prices here can drift from Product.basePrice. Replace with the DB-backed GET /api/menuboards
// (MenuBoardConfig) and derive sold-out from Product/Modifier.isAvailable (see docs/open-questions.md Q-DM-7, Q-UI-1).
// Kept on purpose: the /boards screen is still needed.
export const CANONICAL_4K_SCREENS: Record<number, SignageScreenConfig> = {
  1: {
    screenNumber: 1,
    title: "DOENER BUNS, MY WRAPS & BIG'S",
    subtitle: "AUTHENTIC ROTISSERIE CARVED TO ORDER",
    layoutType: "PRICE_MATRIX",
    activeDaypart: "AUTO",
    bannerMessage: "100% CARAMELIZED ROTISSERIE MEAT · FRESH SESAME FLADENBROT DAILY",
    boardImageUrl: "/assets/boards/board-1-doener-wraps-bigs-bowls.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-hamburg-doner",
        sku: "MYGD-B1-HMB-DONER",
        name: "Hamburg Doener",
        nameDE: "Hamburger Döner Kebab",
        description: "Freshly baked sesame bun loaded with caramelized rotisserie beef, crisp salad & signature sauces",
        priceEUR: 6.95,
        badge: "TOP_SELLER",
        imageUrl: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-chicken-doner",
        sku: "MYGD-B1-CK-DONER",
        name: "Chicken Doener",
        nameDE: "Knuspriger Hähnchen Döner",
        description: "Juicy chicken rotisserie strips in toasted sesame bun with garlic Kräuter sauce",
        priceEUR: 6.95,
        badge: "BESTSELLER",
        imageUrl: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-cheese-doner",
        sku: "MYGD-B1-CHS-DONER",
        name: "Cheese Doener",
        nameDE: "Käse Döner Kebab",
        description: "Rotisserie beef döner topped with melted cheddar & creamy garlic sauce",
        priceEUR: 7.50,
        badge: "POPULAR",
        imageUrl: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-beef-wrap",
        sku: "MYGD-B1-BF-WRAP",
        name: "Beef Wrap",
        nameDE: "Rind Dürüm Wrap",
        description: "Toasted lavash flatbread rolled with tender rotisserie beef and fresh salad",
        priceEUR: 9.90,
        badge: "TOP_SELLER",
        imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-big-b-doner",
        sku: "MYGD-B1-BIG-B",
        name: "Big B Beef Doener",
        nameDE: "Big B XXL Rind Döner",
        description: "Massive triangular sesame Fladenbrot packed with extra rotisserie beef",
        priceEUR: 11.90,
        badge: "CHEF_CHOICE",
        imageUrl: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-beef-bowl",
        sku: "MYGD-B1-BF-BOWL",
        name: "Beef Bowl",
        nameDE: "Berliner Rind Bowl",
        description: "Carved rotisserie beef over fresh red cabbage, crisp cucumber, sweet corn & tomato salad",
        priceEUR: 9.90,
        badge: "HEALTHY",
        imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
    ],
  },
  2: {
    screenNumber: 2,
    title: "MYGD BURGERS, PIZZAS & DOEZZA",
    subtitle: "BERLIN FAST CASUAL INNOVATION",
    layoutType: "PRICE_MATRIX",
    activeDaypart: "AUTO",
    bannerMessage: "STONE-BAKED THIN CRUST PIZZAS & SIGNATURE TRIANGLE DOEZZA SLICES",
    boardImageUrl: "/assets/boards/board-2-burgers-pizzas-doezza.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-beefster",
        sku: "MYGD-B2-BEEFSTER",
        name: "Beefster Burger",
        nameDE: "Beefster Döner Burger",
        description: "Rotisserie beef, melted cheese, crisp lettuce, tomato and signature cocktail sauce in toasted bun",
        priceEUR: 7.95,
        badge: "BESTSELLER",
        imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-cheesy-gd",
        sku: "MYGD-B2-CHEESY-GD",
        name: "Cheesy GD Burger",
        nameDE: "Cheesy GD Doppelkäse Burger",
        description: "Loaded with melted cheddar, double beef döner and garlic herb sauce",
        priceEUR: 9.95,
        badge: "TOP_SELLER",
        imageUrl: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-chicken-hype",
        sku: "MYGD-B2-CK-HYPE",
        name: "Chicken Hype Burger",
        nameDE: "Chicken Hype Burger",
        description: "Tender chicken döner strips with crispy bacon style crust and herb cream",
        priceEUR: 8.50,
        badge: "POPULAR",
        imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-pizza-margherita",
        sku: "MYGD-B2-PZ-MARG",
        name: "Margherita Pizza (33cm)",
        nameDE: "Margherita Steinofen Pizza",
        description: "Italian tomato passata, 100% fior di latte mozzarella, fresh basil & oregano",
        priceEUR: 15.95,
        imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-pizza-salami",
        sku: "MYGD-B2-PZ-SALAMI",
        name: "Salami Pizza (33cm)",
        nameDE: "Salami Steinofen Pizza",
        description: "Crispy beef salami slices, melted mozzarella, garlic infused olive oil",
        priceEUR: 16.95,
        badge: "POPULAR",
        imageUrl: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-doezza-margherita",
        sku: "MYGD-B2-DZ-MARG",
        name: "Doezza Margherita Slice",
        nameDE: "Doezza Margherita Dreieck",
        description: "Crispy triangular Turkish flatbread pizza with melted cheese & tomato herb sauce",
        priceEUR: 6.50,
        badge: "CHEF_CHOICE",
        imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
    ],
  },
  3: {
    screenNumber: 3,
    title: "LOADED FRIES, NUGGETS & WINGS",
    subtitle: "CRISPY STREET FOOD INDULGENCE",
    layoutType: "PRICE_MATRIX",
    activeDaypart: "AUTO",
    bannerMessage: "DOUBLE-COOKED SKIN-ON BERLIN FRIES SMOTHERED IN RICH TOPPINGS",
    boardImageUrl: "/assets/boards/board-3-loaded-fries-nuggets-wings-meatballs.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-cheesy-fries",
        sku: "MYGD-B3-CH-FRIES",
        name: "Cheesy Loaded Fries",
        nameDE: "Käse Loaded Pommes",
        description: "Crispy Berlin fries drenched in warm cheddar cheese sauce, roasted onions & herbs",
        priceEUR: 6.90,
        badge: "TOP_SELLER",
        imageUrl: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-hollandaise-fries",
        sku: "MYGD-B3-HL-FRIES",
        name: "Hollandaise Loaded Fries",
        nameDE: "Hollandaise Loaded Pommes",
        description: "Crispy fries topped with creamy Hollandaise sauce and rotisserie meat crunch",
        priceEUR: 6.90,
        badge: "CHEF_CHOICE",
        imageUrl: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-jalapeno-fries",
        sku: "MYGD-B3-JAL-FRIES",
        name: "Jalapeño Sour Cream Fries",
        nameDE: "Jalapeño Sauerrahm Pommes",
        description: "Spicy pickled jalapeño rings, cool sour cream drizzle, spring onions",
        priceEUR: 6.90,
        badge: "SPICY_KICK",
        imageUrl: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-nuggets-6",
        sku: "MYGD-B3-NUG-6",
        name: "Chicken Nuggets (6 Pcs)",
        nameDE: "Hähnchen Nuggets (6 Stk)",
        description: "100% crispy chicken breast bites served golden with signature dip",
        priceEUR: 4.90,
        badge: "BESTSELLER",
        imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-wings-6",
        sku: "MYGD-B3-WNG-6",
        name: "Chicken Wings (6 Pcs)",
        nameDE: "Knusprige Chicken Wings (6 Stk)",
        description: "Crispy marinated hot wings glazed with spicy barbecue herb crunch",
        priceEUR: 5.90,
        badge: "POPULAR",
        imageUrl: "https://images.unsplash.com/photo-1527477378408-1bc09c21311b?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-meatballs-6",
        sku: "MYGD-B3-MB-6",
        name: "Berlin Meatballs (6 Pcs)",
        nameDE: "Berliner Köfte Fleischbällchen (6 Stk)",
        description: "Spiced beef meatballs with sumac onion salad and garlic dip",
        priceEUR: 5.90,
        badge: "NEW",
        imageUrl: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
    ],
  },
  4: {
    screenNumber: 4,
    title: "MYGD DRINKS, BEER & COFFEE",
    subtitle: "REFRESHING REHYDRATION & SPECIALTY BREWS",
    layoutType: "DRINKS_SIDES",
    activeDaypart: "AUTO",
    bannerMessage: "GERMAN IMPORTED BEERS, AYRAN, CHILLED SMOOTHIES & ROASTED ESPRESSO",
    boardImageUrl: "/assets/boards/board-4-drinks-beers-smoothies-coffee.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-hofbrau-orig",
        sku: "MYGD-B4-HB-ORIG",
        name: "Hofbräu Original (0.5L)",
        nameDE: "Hofbräu München Original",
        description: "Imported Munich Bavarian pale lager with crisp malt and herbal hop balance",
        priceEUR: 5.00,
        badge: "TOP_SELLER",
        imageUrl: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-ayran-500",
        sku: "MYGD-B4-AYRAN-500",
        name: "Authentic Chilled Ayran (0.5L)",
        nameDE: "Traditioneller Ayran (0.5L)",
        description: "Traditional chilled Turkish yogurt, sea salt & water beverage",
        priceEUR: 3.50,
        badge: "BESTSELLER",
        imageUrl: "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-coke-postmix",
        sku: "MYGD-B4-COKE-PM",
        name: "Coca-Cola / Zero (Postmix)",
        nameDE: "Coca-Cola / Zero Frischgezapft",
        description: "Chilled fountain beverage served over crushed ice",
        priceEUR: 2.50,
        imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-smoothie-tropical",
        sku: "MYGD-B4-SM-TROP",
        name: "Tropical Twist Smoothie",
        nameDE: "Tropischer Mango-Maracuja Smoothie",
        description: "Pure Alphonso mango, passionfruit, pineapple & banana blend",
        priceEUR: 2.99,
        badge: "POPULAR",
        imageUrl: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-shake-strawberry",
        sku: "MYGD-B4-SHK-STRW",
        name: "Strawberry Milkshake",
        nameDE: "Erdbeer Milchshake",
        description: "Hand-spun rich ice cream shake with pure strawberry swirl",
        priceEUR: 2.90,
        imageUrl: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-coffee-cappuccino",
        sku: "MYGD-B4-COF-CAP",
        name: "Cappuccino Italiano",
        nameDE: "Italienischer Cappuccino",
        description: "Freshly ground double espresso shot with silky micro-foamed milk",
        priceEUR: 3.50,
        imageUrl: "https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
    ],
  },
  5: {
    screenNumber: 5,
    title: "FINGERFOOD, SIDES & KIDS MEAL",
    subtitle: "SMALL BITES BE HAPPINESS",
    layoutType: "SPLIT_COMBO",
    activeDaypart: "AUTO",
    bannerMessage: "CRISPY SIDES & VALUE KIDS MEAL (€5.00) WITH KINDER RIEGEL SURPRISE",
    boardImageUrl: "/assets/boards/board-5-sides-fries-kids-meal.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-mozzarella-6",
        sku: "MYGD-B5-MOZZ-6",
        name: "Mozzarella Sticks (6 Pcs)",
        nameDE: "Mozzarella Sticks (6 Stk)",
        description: "Golden crumbed mozzarella with stretchy melted cheese core and dip",
        priceEUR: 6.90,
        badge: "POPULAR",
        imageUrl: "https://images.unsplash.com/photo-1548340748-6d2b7d7da280?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-onion-rings-6",
        sku: "MYGD-B5-ONION-6",
        name: "Onion Rings (6 Pcs)",
        nameDE: "Zwiebelringe im Bierteig (6 Stk)",
        description: "Crispy beer-battered sweet onion rings with smoky dip",
        priceEUR: 6.90,
        badge: "VEGGIE",
        imageUrl: "https://images.unsplash.com/photo-1639024471287-032f66e57973?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-fries-regular",
        sku: "MYGD-B5-FR-REG",
        name: "MYGD Fries (Regular)",
        nameDE: "Berliner Pommes (Normal)",
        description: "Double-fried golden skin-on fries with paprika sea salt",
        priceEUR: 2.50,
        largePriceEUR: 3.50,
        badge: "BESTSELLER",
        imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-sweet-potato-fries",
        sku: "MYGD-B5-SWT-FR",
        name: "Sweet Potato Fries (Regular)",
        nameDE: "Süßkartoffel Pommes (Normal)",
        description: "Crispy sweet potato fries served hot with herb dip",
        priceEUR: 2.90,
        largePriceEUR: 3.90,
        badge: "CHEF_CHOICE",
        imageUrl: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
      {
        id: "item-kids-meal",
        sku: "MYGD-B5-KIDS-MEAL",
        name: "MYGD Kids Meal Box",
        nameDE: "MYGD Kinder Menü Box",
        description: "Choose Main (Kids Doener / Nuggets / Meatballs) + Small Fries + Drink (Water / Juice) + 1 Kinder Riegel",
        priceEUR: 5.00,
        badge: "TOP_SELLER",
        imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=85",
        isAvailable: true,
      },
    ],
  },
};
