// MY GERMAN DÖNER — 4K Dynamic Menu Board Engine
import { SignageScreenConfig } from "./signage.schema";

export const CANONICAL_4K_SCREENS: Record<number, SignageScreenConfig> = {
  1: {
    screenNumber: 1,
    title: "BERLIN SIDES & STREET SPECIALS",
    subtitle: "AUTHENTIC SIDES & SAUCES",
    layoutType: "DRINKS_SIDES",
    activeDaypart: "AUTO",
    bannerMessage: "CRISPY BERLIN FRIES COOKED IN 100% VEGETABLE OIL",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "side-currywurst",
        sku: "MYGD-CURRYWURST",
        name: "Berlin Currywurst Special",
        nameDE: "Original Berliner Currywurst",
        description: "Steamed-then-fried German bratwurst drenched in spiced curry ketchup with skin-on fries",
        priceEUR: 6.5,
        badge: "TOP_SELLER",
        isAvailable: true,
      },
      {
        id: "side-fries-berlin",
        sku: "MYGD-FRIES-REG",
        name: "Crispy Berlin Fries",
        nameDE: "Berliner Pommes Frites",
        description: "Double-cooked crispy skin-on potato fries dusted with signature paprika sea salt",
        priceEUR: 3.5,
        largePriceEUR: 4.5,
        isAvailable: true,
      },
      {
        id: "side-halloumi",
        sku: "MYGD-HALLOUMI-SIDE",
        name: "Grilled Cyprus Halloumi Sticks",
        description: "Charcoal-grilled authentic PDO Cyprus halloumi slices with dried mint",
        priceEUR: 4.0,
        badge: "VEGGIE",
        isAvailable: true,
      },
      {
        id: "side-feta",
        sku: "MYGD-FETA-SIDE",
        name: "Greek Feta Bowl",
        description: "Block-cut sheep's milk feta marinated in extra virgin olive oil and oregano",
        priceEUR: 3.5,
        badge: "VEGGIE",
        isAvailable: true,
      },
    ],
  },
  2: {
    screenNumber: 2,
    title: "AUTHENTIC BERLIN DÖNER KEBAB",
    subtitle: "THE FIRST REAL GERMAN DÖNER IN CYPRUS",
    layoutType: "PRICE_MATRIX",
    activeDaypart: "LUNCH",
    bannerMessage: "100% CARAMELIZED ROTISSERIE MEAT · FRESH SESAME FLADENBROT DAILY",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-classic-doner",
        sku: "MYGD-CL-DONER",
        name: "The Classic Berlin Döner",
        nameDE: "Der Klassische Berliner Döner",
        description:
          "Fluffy freshly baked sesame Fladenbrot, 150g caramelized veal/beef spit meat, crisp red cabbage, fresh tomatoes, sliced cucumbers, onions with sumac, signature Kräuter & Knoblauch sauces.",
        priceEUR: 7.5,
        largePriceEUR: 9.5,
        badge: "TOP_SELLER",
        modifiers: ["Extra Meat (+€2.50)", "Grilled Halloumi (+€1.00)", "Greek Feta (+€1.00)"],
        isAvailable: true,
      },
      {
        id: "item-doner-box",
        sku: "MYGD-BOX-DONER",
        name: "Berlin Döner Box",
        nameDE: "Original Berliner Döner Box",
        description:
          "150g rotisserie carved spit meat over golden crispy Berlin fries, pickled cabbage, spicy Scharf chili drizzle.",
        priceEUR: 8.5,
        badge: "SPICY_KICK",
        modifiers: ["Extra Meat (+€2.50)", "Fries Inside", "Jalapeño Kick"],
        isAvailable: true,
      },
      {
        id: "item-durum-wrap",
        sku: "MYGD-DURUM-WRAP",
        name: "Dürüm Wrap Roll",
        nameDE: "Berliner Dürüm Rolle",
        description:
          "Fresh toasted flatbread rolled with crisp salad, roasted peppers, creamy garlic sauce, and 150g spit meat.",
        priceEUR: 8.0,
        badge: "CHEF_CHOICE",
        modifiers: ["Mild to Level 5 Hölle!", "Extra Halloumi (+€1.00)"],
        isAvailable: true,
      },
    ],
  },
  3: {
    screenNumber: 3,
    title: "DRINKS, AYRAN & COMBO UPGRADE",
    subtitle: "REFRESHING REHYDRATION",
    layoutType: "SPLIT_COMBO",
    activeDaypart: "AUTO",
    bannerMessage: "MAKE IT A MEAL COMBO (+€3.50): FRIES + SOFT DRINK OR AYRAN",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "drink-ayran",
        sku: "MYGD-AYRAN",
        name: "Traditional Turkish Ayran",
        description: "Chilled yogurt, water, and sea salt drink - the ultimate döner companion",
        priceEUR: 2.0,
        isAvailable: true,
      },
      {
        id: "drink-coke",
        sku: "MYGD-COKE-CAN",
        name: "Coca-Cola Original 330ml",
        priceEUR: 2.0,
        isAvailable: true,
      },
      {
        id: "drink-coke-zero",
        sku: "MYGD-COKE-ZERO",
        name: "Coca-Cola Zero Sugar 330ml",
        priceEUR: 2.0,
        isAvailable: true,
      },
      {
        id: "drink-german-beer",
        sku: "MYGD-BEER-PILSNER",
        name: "Krombacher Pilsner 500ml",
        description: "Crisp German imported pilsner lager",
        priceEUR: 3.5,
        isAvailable: true,
      },
    ],
  },
  4: {
    screenNumber: 4,
    title: "BRAND HERITAGE & PROMO SHOWCASE",
    subtitle: "BITE THE HYPE",
    layoutType: "PROMO_HERO",
    activeDaypart: "AUTO",
    bannerMessage: "STORE 01: EMBA (PAPHOS) · STORE 02: LIMASSOL MARINA",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "promo-hype-meal",
        sku: "MYGD-HYPE-MEAL",
        name: "The Hype Meal Combo (+€3.50)",
        description: "Upgrade any Döner Sandwich or Dürüm with crispy Berlin Fries and 330ml drink or authentic Ayran.",
        priceEUR: 3.5,
        badge: "TOP_SELLER",
        isAvailable: true,
      },
    ],
  },
};
