// MY GERMAN DÖNER — 4K Dynamic Menu Board Engine
import { SignageScreenConfig } from "./signage.schema";

export const CANONICAL_4K_SCREENS: Record<number, SignageScreenConfig> = {
  1: {
    screenNumber: 1,
    title: "DOENER BUNS, MY WRAPS & BIG'S",
    subtitle: "AUTHENTIC ROTISSERIE CARVED TO ORDER",
    layoutType: "PRICE_MATRIX",
    activeDaypart: "AUTO",
    bannerMessage: "100% CARAMELIZED ROTISSERIE MEAT · FRESH SESAME FLADENBROT DAILY",
    boardImageUrl: "/assets/boards/board-1-doener-wraps-bigs-bowls.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-hamburg-doner",
        sku: "MYGD-B1-HMB-DONER",
        name: "Hamburg Doener",
        nameDE: "Hamburger Döner Kebab",
        description: "Freshly baked sesame bun loaded with caramelized rotisserie beef, crisp salad & signature sauces (Ketchup, Mayo, Mustard)",
        priceEUR: 6.90,
        badge: "TOP_SELLER",
        imageUrl: "/assets/menu/products/hamburg-doener.jpg",
        isAvailable: true,
      },
      {
        id: "item-chicken-doner",
        sku: "MYGD-B1-CK-DONER",
        name: "Chicken Doener",
        nameDE: "Knuspriger Hähnchen Döner",
        description: "Juicy chicken rotisserie strips in toasted sesame bun with garlic & Kräuter sauces",
        priceEUR: 6.90,
        badge: "BESTSELLER",
        imageUrl: "/assets/menu/products/chicken-doener.webp",
        isAvailable: true,
      },
      {
        id: "item-cheese-doner",
        sku: "MYGD-B1-CHS-DONER",
        name: "Cheese Doener",
        nameDE: "Käse Döner Kebab",
        description: "Rotisserie beef döner topped with melted cheddar & savory BBQ sauce",
        priceEUR: 7.50,
        badge: "POPULAR",
        imageUrl: "/assets/menu/products/cheese-doener.webp",
        isAvailable: true,
      },
      {
        id: "item-cheese-chicken-doner",
        sku: "MYGD-B1-CHS-CK-DONER",
        name: "Cheese Chicken Doener",
        nameDE: "Käse Hähnchen Döner",
        description: "Chicken doener, melted cheese, crisp salad and signature sauces",
        priceEUR: 7.50,
        imageUrl: "/assets/menu/products/cheese-chicken-doener.webp",
        isAvailable: true,
      },
      {
        id: "item-beef-wrap",
        sku: "MYGD-B1-BF-WRAP",
        name: "Beef Wrap",
        nameDE: "Rind Dürüm Wrap",
        description: "Toasted lavash flatbread rolled with tender rotisserie beef, salad and cocktail sauce",
        priceEUR: 9.90,
        badge: "TOP_SELLER",
        imageUrl: "/assets/menu/products/beef-wrap.jpg",
        isAvailable: true,
      },
      {
        id: "item-big-b-doner",
        sku: "MYGD-B1-BIG-B",
        name: "Big B Beef Doener",
        nameDE: "Big B XXL Rind Döner",
        description: "Massive triangular sesame Fladenbrot packed with extra rotisserie beef and cocktail sauce",
        priceEUR: 11.90,
        badge: "CHEF_CHOICE",
        imageUrl: "/assets/menu/products/big-b-doener.jpg",
        isAvailable: true,
      },
      {
        id: "item-beef-bowl",
        sku: "MYGD-B1-BF-BOWL",
        name: "Beef Bowl",
        nameDE: "Berliner Rind Bowl",
        description: "Carved rotisserie beef over white rice or crunchy fries, red cabbage, cucumber & tomato salad",
        priceEUR: 9.90,
        badge: "HEALTHY",
        imageUrl: "/assets/menu/products/doener-bowl.jpg",
        isAvailable: true,
      },
    ],
  },
  2: {
    screenNumber: 2,
    title: "MYGD PIZZAS, TACOS & BURGERS",
    subtitle: "BERLIN FAST CASUAL INNOVATION",
    layoutType: "PRICE_MATRIX",
    activeDaypart: "AUTO",
    bannerMessage: "SECOND PIZZA 20% OFF · CRISPY TACOS & SIGNATURE DOEZZA SLICES",
    boardImageUrl: "/assets/boards/board-2-burgers-pizzas-doezza.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-chicken-doener-pizza",
        sku: "MYGD-PZ-CK-DONER",
        name: "Chicken Doener Pizza (33cm)",
        nameDE: "Hähnchen Döner Pizza",
        description: "Tomato sauce, mozzarella, roasted chicken doener, tomatoes, onions, garlic sauce drizzle",
        priceEUR: 17.90,
        badge: "BESTSELLER",
        imageUrl: "/assets/menu/products/chicken-doener-pizza.jpg",
        isAvailable: true,
      },
      {
        id: "item-pizza-margherita",
        sku: "MYGD-B2-PZ-MARG",
        name: "Margherita Pizza (33cm)",
        nameDE: "Margherita Steinofen Pizza",
        description: "Italian tomato passata, 100% fior di latte mozzarella, fresh tomatoes & basil",
        priceEUR: 15.90,
        imageUrl: "/assets/menu/products/pizza-margherita.webp",
        isAvailable: true,
      },
      {
        id: "item-pizza-salami",
        sku: "MYGD-B2-PZ-SALAMI",
        name: "Salami Pizza (33cm)",
        nameDE: "Salami Steinofen Pizza",
        description: "Crispy beef salami slices, melted mozzarella, fresh tomatoes",
        priceEUR: 16.90,
        badge: "POPULAR",
        imageUrl: "/assets/menu/products/pizza-salami.webp",
        isAvailable: true,
      },
      {
        id: "item-pizza-five-cheese",
        sku: "MYGD-PZ-5-CHEESE",
        name: "Five Cheese Pizza (33cm)",
        nameDE: "Fünf Käse Steinofen Pizza",
        description: "Tomato sauce, mozzarella, gorgonzola, edam, gouda, feta",
        priceEUR: 17.50,
        badge: "CHEF_CHOICE",
        imageUrl: "/assets/menu/products/pizza-five-cheese.webp",
        isAvailable: true,
      },
      {
        id: "item-beef-taco",
        sku: "MYGD-TC-BEEF",
        name: "Crispy Beef Taco",
        nameDE: "Knuspriger Rind Taco",
        description: "Crunchy taco shell, beef, onions, lettuce, cucumber, tomato, red cabbage, BBQ sauce (1 for €3.50, 4 for €11.90)",
        priceEUR: 3.50,
        badge: "POPULAR",
        imageUrl: "/assets/menu/products/beef-taco.jpg",
        isAvailable: true,
      },
      {
        id: "item-doezza-margherita",
        sku: "MYGD-B2-DZ-MARG",
        name: "Doezza Margherita Slice",
        nameDE: "Doezza Margherita Dreieck",
        description: "Crispy triangular Turkish flatbread pizza with melted cheese & tomato herb sauce",
        priceEUR: 6.50,
        badge: "COMING_SOON",
        imageUrl: "/assets/menu/products/doezza-margherita.webp",
        isAvailable: true,
      },
      {
        id: "item-beefster",
        sku: "MYGD-B2-BEEFSTER",
        name: "Beefster Burger",
        nameDE: "Beefster Döner Burger",
        description: "Rotisserie beef, melted cheese, crisp lettuce, tomato, cocktail sauce in toasted bun",
        priceEUR: 7.95,
        badge: "COMING_SOON",
        imageUrl: "/assets/menu/products/burger-beefster.webp",
        isAvailable: true,
      },
    ],
  },
  3: {
    screenNumber: 3,
    title: "LOADED FRIES, FINGERFOOD & SALADS",
    subtitle: "CRISPY STREET FOOD INDULGENCE",
    layoutType: "PRICE_MATRIX",
    activeDaypart: "AUTO",
    bannerMessage: "MAKE IT A MENU: FRIES OR RICE + 0.4L DRINK (+€3.00) · 1 SAUCE INCLUDED",
    boardImageUrl: "/assets/boards/board-3-loaded-fries-nuggets-wings-meatballs.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-cheesy-fries",
        sku: "MYGD-B3-CH-FRIES",
        name: "Cheesy Loaded Fries",
        nameDE: "Käse Loaded Pommes",
        description: "Crispy Berlin fries drenched in warm cheddar cheese sauce, roasted bits & herbs",
        priceEUR: 7.90,
        badge: "BESTSELLER",
        imageUrl: "/assets/menu/products/cheesy-fries.jpg",
        isAvailable: true,
      },
      {
        id: "item-hollandaise-fries",
        sku: "MYGD-B3-HL-FRIES",
        name: "Hollandaise Loaded Fries",
        nameDE: "Hollandaise Loaded Pommes",
        description: "Crispy fries topped with rich velvety Hollandaise sauce and herbs",
        priceEUR: 7.90,
        badge: "CHEF_CHOICE",
        imageUrl: "/assets/menu/products/loaded-hollandaise.webp",
        isAvailable: true,
      },
      {
        id: "item-jalapeno-fries",
        sku: "MYGD-B3-JAL-FRIES",
        name: "Jalapeño Sour Cream Fries",
        nameDE: "Jalapeño Sauerrahm Pommes",
        description: "Spicy pickled jalapeño rings, cool sour cream drizzle, spring onions",
        priceEUR: 7.90,
        badge: "SPICY",
        imageUrl: "/assets/menu/products/loaded-jalapeno.webp",
        isAvailable: true,
      },
      {
        id: "item-meatballs-6",
        sku: "MYGD-B3-MB-6",
        name: "Meatballs with Fries or Rice (6 Pcs)",
        nameDE: "Berliner Fleischbällchen (6 Stk)",
        description: "Spiced meatballs served with crispy fries or steamed rice, 1 sauce included",
        priceEUR: 7.50,
        badge: "POPULAR",
        imageUrl: "/assets/menu/products/meatballs.webp",
        isAvailable: true,
      },
      {
        id: "item-mozzarella-6",
        sku: "MYGD-B5-MOZZ-6",
        name: "Mozzarella Sticks (6 Pcs)",
        nameDE: "Mozzarella Sticks (6 Stk)",
        description: "Golden crumbed mozzarella with stretchy melted cheese core and dip",
        priceEUR: 5.90,
        badge: "POPULAR",
        imageUrl: "/assets/menu/products/mozzarella-sticks.webp",
        isAvailable: true,
      },
      {
        id: "item-onion-rings-6",
        sku: "MYGD-B5-ONION-6",
        name: "Onion Rings (6 Pcs)",
        nameDE: "Zwiebelringe im Bierteig (6 Stk)",
        description: "Crispy beer-battered sweet onion rings with dip",
        priceEUR: 1.95,
        badge: "VEGGIE",
        imageUrl: "/assets/menu/products/onion-rings.webp",
        isAvailable: true,
      },
      {
        id: "item-chicken-salad",
        sku: "MYGD-SL-CHICKEN",
        name: "Chicken Salad",
        nameDE: "Hähnchen Salat",
        description: "Lettuce, cucumber, tomato, red cabbage, onion, carved chicken, vinegar & oil dressing",
        priceEUR: 8.90,
        imageUrl: "/assets/menu/products/salad-chicken.webp",
        isAvailable: true,
      },
      {
        id: "item-halloumi-salad",
        sku: "MYGD-SL-HALLOUMI",
        name: "Halloumi Salad",
        nameDE: "Halloumi Salat",
        description: "Lettuce, cucumber, tomato, red cabbage, onion, grilled Cyprus halloumi, vinaigrette",
        priceEUR: 8.90,
        badge: "CHEF_CHOICE",
        imageUrl: "/assets/menu/products/salad-halloumi.webp",
        isAvailable: true,
      },
    ],
  },
  4: {
    screenNumber: 4,
    title: "MYGD DRINKS, BEER & COFFEE",
    subtitle: "REFRESHING REHYDRATION & SPECIALTY BREWS",
    layoutType: "DRINKS_SIDES",
    activeDaypart: "AUTO",
    bannerMessage: "GERMAN IMPORTED BEERS, AYRAN, CHILLED SMOOTHIES & ROASTED ESPRESSO",
    boardImageUrl: "/assets/boards/board-4-drinks-beers-smoothies-coffee.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-hofbrau-draft",
        sku: "MYGD-B4-HB-DFT",
        name: "Hofbräu München Draft (0.5L)",
        nameDE: "Hofbräu München Frischgezapft (0.5L)",
        description: "Imported Munich Bavarian pale lager with crisp malt and herbal hop balance",
        priceEUR: 6.00,
        badge: "TOP_SELLER",
        imageUrl: "/assets/menu/products/drink-draft-beer.webp",
        isAvailable: true,
      },
      {
        id: "item-hofbrau-orig",
        sku: "MYGD-B4-HB-ORIG",
        name: "Hofbräu Original / Helles (0.5L)",
        nameDE: "Hofbräu München Flasche",
        description: "Classic Munich bottled Bavarian lager",
        priceEUR: 5.00,
        imageUrl: "/assets/menu/products/drink-bottled-beer.webp",
        isAvailable: true,
      },
      {
        id: "item-ayran-500",
        sku: "MYGD-B4-AYRAN-500",
        name: "Authentic Chilled Ayran (0.5L)",
        nameDE: "Traditioneller Ayran (0.5L)",
        description: "Traditional chilled Turkish yogurt, sea salt & water beverage",
        priceEUR: 3.50,
        badge: "BESTSELLER",
        imageUrl: "/assets/menu/products/water-ayran.webp",
        isAvailable: true,
      },
      {
        id: "item-soda-postmix",
        sku: "MYGD-B4-SODA-PM",
        name: "Soft Drinks Postmix (0.4L)",
        nameDE: "Softdrink Frischgezapft",
        description: "Coca-Cola, Coke Zero, Fanta Zero, Sprite, Sprite Zero, Sparkling Water",
        priceEUR: 2.50,
        imageUrl: "/assets/menu/products/drink-postmix-soda.webp",
        isAvailable: true,
      },
      {
        id: "item-canned-tea",
        sku: "MYGD-B4-CAN-TEA",
        name: "Canned Drinks / Lipton Ice Tea",
        nameDE: "Dosengetränke / Eistee",
        description: "Fanta Lemon, Fanta Zero, Lipton Ice Tea Peach, Peach Zero, Ice Tea Lemon",
        priceEUR: 2.50,
        imageUrl: "/assets/menu/products/drink-canned-soda.webp",
        isAvailable: true,
      },
      {
        id: "item-coffee-cappuccino",
        sku: "MYGD-B4-COF-CAP",
        name: "Cappuccino Italiano / Latte",
        nameDE: "Italienischer Cappuccino",
        description: "Freshly ground double espresso shot with silky micro-foamed milk",
        priceEUR: 3.00,
        imageUrl: "/assets/menu/products/coffee-cappuccino.webp",
        isAvailable: true,
      },
    ],
  },
  5: {
    screenNumber: 5,
    title: "FINGERFOOD, SIDES & KIDS MEAL",
    subtitle: "SMALL BITES BIG HAPPINESS",
    layoutType: "SPLIT_COMBO",
    activeDaypart: "AUTO",
    bannerMessage: "KIDS MEAL (€5.00) WITH KINDER RIEGEL · CRUNCHY FRIES, NUGGETS & WINGS",
    boardImageUrl: "/assets/boards/board-5-sides-fries-kids-meal.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-kids-meal",
        sku: "MYGD-B5-KIDS-MEAL",
        name: "MYGD Kids Meal Box",
        nameDE: "MYGD Kinder Menü Box",
        description: "Main (Kids Doener / 4 Nuggets / 4 Meatballs) + Small Fries + Drink Choice + 1 Kinder Riegel chocolate bar",
        priceEUR: 5.00,
        badge: "TOP_SELLER",
        imageUrl: "/assets/menu/products/kids-meal.webp",
        isAvailable: true,
      },
      {
        id: "item-nuggets-6",
        sku: "MYGD-B3-NUG-6",
        name: "Chicken Nuggets (6 Pcs)",
        nameDE: "Hähnchen Nuggets (6 Stk)",
        description: "100% crispy chicken breast bites with signature dip (6pc: €4.90 / 12pc: €7.90 / 20pc: €11.90)",
        priceEUR: 4.90,
        badge: "BESTSELLER",
        imageUrl: "/assets/menu/products/chicken-nuggets.webp",
        isAvailable: true,
      },
      {
        id: "item-wings-6",
        sku: "MYGD-B3-WNG-6",
        name: "Chicken Wings (6 Pcs)",
        nameDE: "Knusprige Chicken Wings (6 Stk)",
        description: "Crispy marinated hot wings glazed with spicy barbecue herb crunch (6pc: €5.90 / 12pc: €9.90 / 20pc: €14.90)",
        priceEUR: 5.90,
        badge: "POPULAR",
        imageUrl: "/assets/menu/products/chicken-wings.webp",
        isAvailable: true,
      },
      {
        id: "item-fries-regular",
        sku: "MYGD-B5-FR-REG",
        name: "Crunchy Fries (Regular)",
        nameDE: "Knusprige Pommes (Normal)",
        description: "Double-fried golden skin-on fries with paprika sea salt (Reg: €2.50 / Large: €3.50 / XL: €4.50)",
        priceEUR: 2.50,
        badge: "BESTSELLER",
        imageUrl: "/assets/menu/products/crunchy-fries.webp",
        isAvailable: true,
      },
      {
        id: "item-sweet-potato-fries",
        sku: "MYGD-B5-SWT-FR",
        name: "Sweet Potato Fries (Regular)",
        nameDE: "Süßkartoffel Pommes (Normal)",
        description: "Crispy sweet potato fries (Reg: €2.90 / Large: €3.90 / XL: €4.90)",
        priceEUR: 2.90,
        badge: "CHEF_CHOICE",
        imageUrl: "/assets/menu/products/sweet-potato-fries.webp",
        isAvailable: true,
      },
    ],
  },
  6: {
    screenNumber: 6,
    title: "SMOOTHIES, SHAKES & KOMBUCHA",
    subtitle: "COLD-PRESSED FRUITS & PROBIOTICS",
    layoutType: "DRINKS_SIDES",
    activeDaypart: "AUTO",
    bannerMessage: "100% PURE FRUIT SMOOTHIES (€2.99) · RICH MILKSHAKES (€2.90) · ORGANIC KOMBUCHA",
    boardImageUrl: "/assets/boards/board-6-smoothies-shakes-kombucha.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-smoothie-blend",
        sku: "MYGD-B6-SMOOTHIE",
        name: "Fruit Smoothies (0.4L)",
        nameDE: "Frucht-Smoothies (0.4L)",
        description: "Tropical Twist, Berry Booster, Green Power, or Sunset Delight",
        priceEUR: 2.99,
        badge: "POPULAR",
        imageUrl: "/assets/menu/products/smoothies-blend.webp",
        isAvailable: true,
      },
      {
        id: "item-milkshake-trio",
        sku: "MYGD-B6-SHAKE",
        name: "Hand-Spun Milkshakes (0.4L)",
        nameDE: "Eis-Milchshakes (0.4L)",
        description: "Strawberry, Vanilla, or Chocolate with whipped cream",
        priceEUR: 2.90,
        imageUrl: "/assets/menu/products/milkshakes-trio.webp",
        isAvailable: true,
      },
      {
        id: "item-kombucha-gaia",
        sku: "MYGD-B6-KOMBUCHA",
        name: "Gaia Organic Kombucha (330ml)",
        nameDE: "Gaia Bio-Kombucha (330ml)",
        description: "Hibiscus, Lemon Zen, Ginger Insight, or Lemongrass Unity",
        priceEUR: 3.50,
        imageUrl: "/assets/menu/products/kombucha-gaia.webp",
        isAvailable: true,
      },
      {
        id: "item-red-bull",
        sku: "MYGD-B6-REDBULL",
        name: "Red Bull Energy Drink",
        nameDE: "Red Bull Energy Drink",
        description: "Classic or Sugar Free (250ml)",
        priceEUR: 3.00,
        imageUrl: "/assets/menu/products/red-bull.webp",
        isAvailable: true,
      },
      {
        id: "item-coco-loco",
        sku: "MYGD-B6-COCO",
        name: "Coco Loco Coconut Water",
        nameDE: "Coco Loco Kokoswasser",
        description: "100% Pure Natural Coconut Water (325ml)",
        priceEUR: 2.50,
        imageUrl: "/assets/menu/products/coco-loco.webp",
        isAvailable: true,
      },
    ],
  },
  7: {
    screenNumber: 7,
    title: "CHOOSE YOUR SAUCE",
    subtitle: "11 SIGNATURE HOMEMADE DIPS",
    layoutType: "PRICE_MATRIX",
    activeDaypart: "AUTO",
    bannerMessage: "CRAFTED FRESH DAILY · GARLIC · BBQ · HONEY MUSTARD · CHEESE HOT · TZATZIKI",
    boardImageUrl: "/assets/boards/board-7-sauces-showcase.jpg",
    updatedAt: new Date().toISOString(),
    items: [
      {
        id: "item-sauce-garlic",
        sku: "MYGD-SAUCE-GARLIC",
        name: "Garlic Sauce",
        nameDE: "Knoblauchsauce",
        description: "Creamy homemade garlic herb sauce",
        priceEUR: 0.50,
        badge: "BESTSELLER",
        imageUrl: "/assets/menu/sauces/sauce-garlic.webp",
        isAvailable: true,
      },
      {
        id: "item-sauce-cheese-hot",
        sku: "MYGD-SAUCE-CHS-HOT",
        name: "Cheese Hot Sauce",
        nameDE: "Scharfe Käsesauce",
        description: "Spicy melted cheese dip with chili flakes",
        priceEUR: 0.50,
        badge: "SPICY",
        imageUrl: "/assets/menu/sauces/sauce-cheese-hot.webp",
        isAvailable: true,
      },
      {
        id: "item-sauce-tzatziki",
        sku: "MYGD-SAUCE-TZATZIKI",
        name: "Tzatziki Sauce",
        nameDE: "Griechisches Tzatziki",
        description: "Authentic Greek yogurt, cucumber, garlic and dill",
        priceEUR: 0.50,
        badge: "POPULAR",
        imageUrl: "/assets/menu/sauces/sauce-tzatziki.webp",
        isAvailable: true,
      },
      {
        id: "item-sauce-vegan-garlic",
        sku: "MYGD-SAUCE-VGN-GARLIC",
        name: "Vegan Garlic Sauce",
        nameDE: "Vegane Knoblauchsauce",
        description: "100% plant-based creamy garlic dip",
        priceEUR: 0.50,
        badge: "VEGGIE",
        imageUrl: "/assets/menu/sauces/sauce-vegan-garlic.webp",
        isAvailable: true,
      },
      {
        id: "item-sauce-cocktail",
        sku: "MYGD-SAUCE-COCKTAIL",
        name: "Cocktail Sauce",
        nameDE: "Cocktailsauce",
        description: "Classic Berlin döner cocktail sauce with paprika",
        priceEUR: 0.50,
        imageUrl: "/assets/menu/sauces/sauce-cocktail.webp",
        isAvailable: true,
      },
      {
        id: "item-sauce-bbq",
        sku: "MYGD-SAUCE-BBQ",
        name: "BBQ Sauce",
        nameDE: "Smoky BBQ Sauce",
        description: "Smoky sweet barbecue dipping sauce",
        priceEUR: 0.50,
        imageUrl: "/assets/menu/sauces/sauce-bbq.webp",
        isAvailable: true,
      },
    ],
  },
};
